ucoin/include/ln.h, ucoin/src/ln/ln.c, ucoind/lnapp.c
タイミングによっては、 `announcement_signatures` の作成時に、 NULLアクセスが発生して異常終了することがある。
おそらく #23 対応の際、 `announcement_signatures` までのconfirmation待ち処理を移動させたことによる副作用で、 `funding_locked` の送信前に `announcement_signatures` を送信しようとしていたのだと思われる。
現象がタイミング依存になり、今発生させることができないので、ひとまずmergeさせて評価する。
----
現象の発見が、元々やろうとしていた「close用のアドレス生成を `shutdown` 受信時に行う」の動作確認中だったため、そちらの変更も混ざっている。
=> Fix announcement sigs

include/ucoind.h, ucoin/include/ln.h, ucoin/src/ln/ln.c, ucoind/lnapp.c
fix #53 
`update_fulfill_htlc` は payment_hashがわかるため idは不要だが、 `update_fail_htlc` はわからないため、 previous idが必要
=> Issue 53 2

.gitmodules, libs/Makefile, update_libs.sh
reduce git clone
* curl --> libcurl4-openssl-dev
* jansson --> libjansson-dev
libsodiumはaptのバージョンが古いため残している。
lmdbはデバッグすることが多いため残したが、いずれ削除したい。
=> reduce submodule

cmn/jsonrpc.c
=> monitoringでdeadlockする

routing/routing.cpp
=> initialize

include/ucoind.h, ucoind/cmd_json.c, ucoind/inc/lnapp.h, ucoind/lnapp.c
init/channel_reestablishの交換前に、JSON-RPCでfundingしようとしたことがあったので、それをやめさせる。
=> BOLTメッセージ初期化完了チェック

ucoin/src/ln/ln.c, ucoin/src/ln/ln_msg_anno.c, ucoind/lnapp.c
当面、mainnetに対応できていないため、chain_hashが不一致の場合は無視する。
- channel_update : DBに保存しない
- open_channel : socket切断
=> Ignore mainnet

ucoin/src/ln/ln.c
`lnd`は5分未送信であれば切断する。
しかし、`ping`に対して`pong`を必ず返すわけでも無いようである。
そうなると、`ping`送信に対する`pong`を待ち続けていると、送信するものが無くなり、5分で切断されてしまう。
やむなく、こうする。
- `ping`送信は、未送信状態が60秒経過したら送信する(bytesは0～255の乱数)
- `pong`受信は、パケットとして正常であればOKとする(num_pong_bytesのチェックをしない)
=> no pong check and send ping always

libs/Makefile
テスト用に別IPアドレスからでもJSON-RPCを受け付けるようにしていたが、元に戻しておく。
=> JSON-RPC only localhost

ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoind/inc/lnapp.h, ucoind/lnapp.c, ucoind/monitoring.c
announcementを一度に相手channelに送信するかどうかチェックしていると、DBのロック時間が長くなる。
announcementのDBはノード内の全チャネルが頻繁に確認するため、長時間ロックするのは望ましくない。
今回はチェックを毎秒行うように誌、「channel_announcement/channel_update」を3つ、「node_announcement」を3つまでチェックするように変更した。
=> Short db lock

ucoind/lnapp.c
getinfoでlast errorを出力する。
-wは使わなくてもよくなるが、残しておく。
=> last err in getinfo

ucoin/gtests/testinc_ln_bolt4.cpp, ucoin/include/ln.h, ucoin/src/ln/ln_onion.c, ucoind/lnapp.c
paymentがupdate_fail_htlcになったときのlast errorで、エラーを返したと思われるノードまでのhop数を返す。
=> onion failのhop数を取得

ucoind/lnapp.c
max_htlc_value_in_flight_msatでUINT64_MAXを与えたが、lndでマイナス値と判断していた。
https://github.com/lightningnetwork/lightning-rfc/issues/385
#178
=> lndはvalueを符号無しとみている？

cmn/btcrpc.c, ucoin/include/ln.h, ucoin/include/ucoin.h, ucoin/src/ln/ln.c, ucoind/monitoring.c
to_remoteは native P2WPKHだが、bitcoindは扱えないため、to_localなどの送金先と同じアドレスに送金する。
=> unilateral/revoked transaction close to_remote pay

ucoind/lnapp.c
=> double quotation

ucoind/monitoring.c
to_remoteに支払う金額がない場合はtx自体作成しない
=> skip no to_remote tx

cmn/conf.c, include/ucoind.h, ucoin/include/ln.h, ucoincli/ucoincli.c, ucoind/cmd_json.c, ucoind/lnapp.c
`feerate_per_kw`がかけ離れてfundingできない場合のために、fund.confで設定可能にする。
未指定時、あるいは0を設定した場合は、bitcoindのestimatefeeで取得した値を4分の1した値を使用する。
=> set feerate_per_kw

ucoin/src/ln/ln_node.c
fix #213 
DBでIPアドレスが指定され、引数でIPアドレスが未指定の場合は、DBを優先させる。
それ以外の場合は、不一致であれば起動させない。
=> ignore no ipaddress

ucoind/lnapp.c
#221 関連
確信は持てないが、ひとまず組み込んでおく。
`revoke_and_ack` 受信でのDB保存は lnapp.cで行われているため、それで反映される予定。
ただ、他のメッセージが割り込むことでDB保存されてしまう可能性がある(`update_fee`など)。
=> commitment_signed受信ではDB保存しない

ucoin/src/ln/ln.c, ucoind/lnapp.c
#221 関連
#226 によってDBの状態があわなくなったので、まずはそれを元に戻す。
また、`channel_reestablish`パラメータの不一致でチャネルを失敗させるのはMUSTではないため、そもそもの #221 が状態不一致によって発生したと考えると、相手のパラメータを受け入れる方が自然かもしれない。
=> revert #226

ucoincli/ucoincli.c, ucoind/cmd_json.c, ucoind/inc/monitoring.h, ucoind/monitoring.c
`ucoincli -s1` : stop auto channel connect
`ucoincli -s0` : start auto channel connect(default)
`ucoincli -c xxx -q`でチャネル切断しても再接続されてしまうので、それを避けるのに利用できる。
=> Autoconn stop

ucoin/src/ln/ln_msg_setupctl.c
fix #287 
ping/pongのignoredチェックを行わない。
c-lightningがDEVELOPER=1のとき、ping/pongのignoredに0以外のデータを送ってくる。
https://github.com/ElementsProject/lightning/commit/b8c636514b08f0c51d77ea6dce9b4ace43711515
https://github.com/ElementsProject/lightning/commit/3c6eec87e38e20e1f1a362ee8642ea3ea7694f3f
=> no ping/pong ignred check

ucoin/src/ln/ln.c
next_local_commitment_numberを補正する
=> channel_reestablishでcommit_numを0で送信してしまう

ucoind/lnapp.c
`init`交換ですりぬけることがあったため、ポーリングに変更する。
=> init wait loop

README.md, cmn/btcrpc.c, include/btcrpc.h, ucoin/include/ln.h, ucoin/src/ln/ln.c, ucoin/src/ucoin.c, ucoind/lnapp.c
fix #297 
`dumpprivkey`を削除し、`signrawtransaction`に置き換える。
=> signrawtransaction

ucoin/include/ln.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_msg_setupctl.c, ucoind/lnapp.c
1. (me)SEND: open_channel
2. (peer)RECV: feerate_per_kw is out of range
3. (peer)SEND: error
4. (peer)disconnect
5. (me)connect
6. (me)SEND: open_channel
3でestablishのメモリ解放ができていないため、6で失敗した。
=> Fix establish release

ucoin/src/ln/ln.c, ucoin/src/ln/ln_signer.c, ucoind/lnapp.c
一度fundingに失敗(feerate_per_kwがあわないなどで、`open_channel`後に失敗)すると、funding後の初回送金で`revoke_and_ack`の`per_commitment_secret`が不一致になる。
=> Fix funding

install/pay_fundin.sh
=> check amount

ucoin/include/ln.h, ucoin/src/ln/ln.c, ucoind/cmd_json.c, ucoind/lnapp.c
bitcoindで`estimatesmartfee 6`で取得した`feerate_per_kb`。
これを4分の1にした値を`feerate_per_kw`としている。
マージンをその1割とし、以下を許容するようにした。
`feerate_per_kw * 0.9 <= value <= feerate_per_kw * 1.1`
=> Check min/max feerate

ucoin/include/ln.h, ucoin/src/ln/ln.c, ucoind/lnapp.c
fix #351 
init受信後、ln_set_establish()呼び出し前にopen_channelを受信してself->p_establishがNULLになるタイミングがある。
=> alloc before init message

cmn/btcrpc.c
=> log: btc response

install/pay_fundin.sh, ucoin/include/ln.h, ucoind/lnapp.c
c-lightningに合わせて、feerate_per_kwの下限を253とする。
=> Feerate min

ucoind/cmd_json.c, ucoind/p2p_cli.c
`ucoincli -c` で接続した際、`init`交換までチェックして結果を返す。
=> json connect check

install/script/error.sh, routing/routing_main.c, ucoin/include/ln.h, ucoin/src/ln/ln_msg_setupctl.c, ucoind/lnapp.c
fix #394 
`isprint()`がfalseの文字が入っている場合はダンプ出力する
=> Error unicode

cmn/misc.c, include/misc.h, ucoind/p2p_cli.c, ucoind/ucoind.c
socket接続失敗時、channel_idがオールゼロの場合はnode接続失敗リストに追加しない。
=> Nodefail ignore

routing/routing_main.c, ucoin/gtests/test_ucoin.cpp, ucoin/gtests/testinc_bech32.cpp, ucoin/include/ln.h, ucoin/include/segwit_addr.h, ucoin/src/bech32/segwit_addr.c, ucoin/src/ln/ln.c, ucoin/src/ln/ln_msg_anno.c, ucoin/src/ln/ln_node.c, ucoin/src/routing/ln_routing.cpp, ucoincli/ucoincli.c, ucoind/cmd_json.c, ucoind/lnapp.c, ucoind/monitoring.c
fix #410 
support BOLT11 r field.
invoiceの"r" fieldは、private channelなどのannounceされていない`channel_update`情報を載せることができる。
routingとしてr fieldの情報を含めるようにした。
こちらのMLは、相手のchannel_updateをもらえないとr fieldに含めることができないので、`channel_announcement`がない状態で`channel_update`を送信することについてであって、本件とは別の内容となる。
https://lists.linuxfoundation.org/pipermail/lightning-dev/2018-April/001220.html
=> BOLT11 rfield

showdb/showdb.c, ucoin/include/ln_db.h, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_node.c, ucoind/lnapp.c
#430 対応 その1
* `channel_announcment` `channel_update` /`node_announcement`の送受信node_idを、起動時にDBから全クリア
* 個別クリアもするので、不要かもしれない
* `channel_announcment` `channel_update` /`node_announcement`の送受信node_idを、channel接続時にDBからクリア
* `channel_announcement`のない`channel_update`は起動時にDBからクリア
* 未送信の`channel_announcment` `channel_update` /`node_announcement`がない場合、次のチェックを30秒後にする(通常は1秒間隔)
#435 のため、対策できたかどうかか確認が取れないため、一度本編にmergeする。
=> #430 part 1

ucoin/src/ln/ln_db_lmdb.c
#443 
DBのトランザクション解放待ちで固まっている可能性があるとして、いくつかreadonlyにした。
が、効果があるのかは長期的に見ないと分からない。
=> MDB_RDONLY

ucoind/lnapp.c
`ucoincli -l` : wait_minimum_depthでもchannel_idを出力する
=> wait_minimum_depth: channel_id

showdb/showdb.c
JSONで、`node_announcement`の`alias`がエスケープされていない。
全文字種はやりたくないので、ダブルクォーテーションだけ行う。
=> escape: double quotation

routing/routing_main.c, ucoin/src/routing/ln_routing.cpp
fix #537 
ルート検索する際、
* channel_announcementデータ
* localのチャネル
を対象にしているつもりだったが、
* channel_announcementデータが1つもない場合、エラーで中断していた
* localチャネルが捨てられていた
となっていたため、localチャネルしかない状態ではルート検索に失敗していた。
=> Fix537 routefail

CHANGELOG.md, ucoin/include/ln_db.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoind/lnapp.c
BOLT#07: `channel_announcement`でnode_idを受信していない`node_announcement`は、無視してよい。
commit db6361137221589af49943287450844f8c394464
Date:   Tue Jun 19 17:50:48 2018 +0900
update readme
commit 2dc1a050f6a449d2494818b6927ae7a3348d557f
Date:   Tue Jun 19 17:45:34 2018 +0900
send my node_announcement
commit 981f48ea7188e8f8c32ae746ba683838ecd200d7
Date:   Tue Jun 19 16:41:46 2018 +0900
lmdb: add "annoinfo_chan"
* channel_announcement保存時に、node1, node2を保存
* node_announcement保存時に"annoinfo_chan"になければ保存しない
=> ignore received `node_announcement` not receiving `channel_announcement`

showdb/showdb.c, ucoin/include/ln_db.h, ucoin/include/segwit_addr.h, ucoin/src/bech32/segwit_addr.c, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoind/cmd_json.c, ucoind/lnapp.c, ucoind/monitoring.c
fix #570
received HTLCが自分のpreimageを参照しているので、invoiceの期限が来ても削除しないようにする。
=> preimage don't remove before related channel close

ucoin/include/ln.h, ucoin/include/ln_db.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_node.c, ucoind/inc/lnapp.h, ucoind/lnapp.c
fix #573 
BOLT#07
「受信済み`channel_announcement`のnode_idに含まれていない`node_announcement`は無視してよい」ため、先に`channel_announcement`を送信する。
=> send `node_announcement` after `channel_announcement`

ucoin/libs/mbedtls_config/check_config.h, ucoin/libs/mbedtls_config/config-ucoin.h, ucoin/src/ln/ln_enc_auth.c
fix #554 
* update: MbedTLS header file
* enable HKDF
unittestだけは通した。
=> use MbedTLS for HKDF

ucoin/src/ln/ln.c
fix #573 part2
以前は`announcement_signatures`が揃ったタイミングで`channel_announcement`などを送信していたため、DB保存と同時に送信済みフラグを立てていた。
#573 修正時にその送信を止めたが、フラグを立てる処理は残していたため、自分の`channel_announcement`などが送信されないようになっていた。
=> channel_announcement don't send exchanging `announcement_signatures`.

ucoin/include/ln.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoind/lnapp.c
fix #441 
announcementを行っていない場合、接続時に自分の`channel_update`を送信する。
そうすることにより、自分のchannelがprivateで、invoiceの`r` fieldに情報を載せることができるようになる(#465 )。
=> send channel_update before announcement

ucoind/btcrpc_bitcoind.c, ucoind/inc/btcrpc.h, ucoind/lnapp.c, ucoind/monitoring.c
bitcoin interface見直し part2
commit 96145504eea5f9ce4a96e47895cebfe50542a3fa
Date:   Wed Jul 4 11:24:35 2018 +0900
API変更
* btcrpc_is_short_channel_unspent() --> TXID取得のみ
* btcrpc_get_unspent_amount(): btcrpc_check_unspent()に統合
commit 2e45063eaaa61bdc7bed28d6758ad29f76365852
Date:   Tue Jul 3 21:01:45 2018 +0900
rename API
commit 9183ed49b4c32d00a8a42dfca7291bf7c871c123
Date:   Tue Jul 3 21:01:37 2018 +0900
comment
=> btc interface part2

include/ucoind.h, ucoind/Makefile, ucoind/cmd_json.c, ucoind/inc/p2p_cli.h, ucoind/lnapp.c, ucoind/monitoring.c, ucoind/p2p_cli.c
lightning-integrationのtest_reconnect[ucoind_lightning]がpassしなかった件に関する修正。
- 対向の`node_announcement`に`addresses`がなかった場合でも、自分がclientであれば前回アプリから渡された接続先に接続する。実際には後者の試行を先に行なっている（ref. `channel_reconnect()`）
- TCPのコネクション確立ができなくても、対向nodeをブラックリストに入れない。`noise_handshake()`が失敗したらブラックリスト入りだったのを、その前に`wait_peer_connected()`を行い、それに失敗したときはブラックリストに入れない。
=> test_reconnect issues

ucoin/include/segwit_addr.h, ucoin/src/bech32/segwit_addr.c, ucoincli/ucoincli.c, ucoind/cmd_json.c
invoice生成の際、min_final_cltv_expiryの設定を可能にする。
`ucoincli -i AMOUNT_MSAT,MIN_FINAL_CLTV_EXPIRY`
=> invoice: min_final_cltv_expiry

.gitignore, Makefile, libs/Makefile, ucoin/Makefile
GNU make が `gmake` `gnumake` になっているような、推奨ビルド環境外を考慮する"おまじない"です。
=> Use `$(MAKE)` instead of `make`

CHANGELOG.md, cmn/conf.c, docs/ucoind.md, include/conf.h, include/ucoind.h, install/default_conf.sh, showdb/showdb.c, ucoin/include/ln.h, ucoin/src/inc/ln/ln_local.h, ucoin/src/inc/ln/ln_signer.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_derkey.c, ucoin/src/ln/ln_msg_anno.c, ucoin/src/ln/ln_msg_establish.c, ucoin/src/ln/ln_signer.c, ucoincli/ucoincli.c, ucoind/cmd_json.c, ucoind/lnapp.c, ucoind/ucoind.c
* send option_data_loss_protect
* receive option_data_loss_protect
* yet "Message Transmission"
commit 259ff1a1eae2e2cb13683906f4fde825811be3a2
Date:   Mon Jul 23 12:20:04 2018 +0900
fail log
commit d5736b3e660f7c2ea8d2070559548401cff6e5c8
Date:   Mon Jul 23 11:47:54 2018 +0900
localfeatures
init_sync and data_loss_protect
commit 4614b750e78a92b8682ba361d7e0919227bba7fc
Date:   Mon Jul 23 11:39:47 2018 +0900
revise signer
commit 8ab56db97dd0efb5aa7bb78fea3e4f796ec20d3a
Date:   Mon Jul 23 08:43:27 2018 +0900
signer整理
commit e80a07c41648882b96c6734e13d384e5f867459c
Date:   Mon Jul 23 08:23:38 2018 +0900 …
=> option_data_loss_protect part1

CHANGELOG.md, ptarm/include/ln.h, ptarm/include/ptarm.h, ptarm/src/ln/ln.c, ptarm/src/ln/ln_db_lmdb.c, ptarm/src/ln/ln_print.c, ptarm/src/ln/ln_script.c, ptarm/src/ln/ln_signer.c, ptarm/src/ptarm_buf.c, ptarm/src/ptarm_tx.c, ptarmcli/ptarmcli.c, ptarmd/cmd_json.c, ptarmd/inc/lnapp.h, ptarmd/lnapp.c, showdb/showdb.c
* DB version -20
* add LN_CB_SEND_QUEUE for re-send
* add ln_self_t: current_commit_num
* fix 2nd HTLC_tx value
commit 62a1c79f7a016d4e4f0e55a419e5b636d2c3db20
Date:   Fri Jul 27 16:22:44 2018 +0900
commit_txはcurrent_commit_numで作成する
commit a864941cb02decec97ff222e274eced9b16cbc0f
Date:   Fri Jul 27 13:58:40 2018 +0900
DB: -20
* add `curremtn_commit_num`
* remove `scriptpubkeys`
* resend `revoke_and_ack`
* resend `commitment_signed`(no good)
commit fcd6ebf31f75d1f06b160c5176640f60c630f40c
Date:   Thu Jul 26 21:25:10 2018 +0900
log
commit 37997b69174d5567b41b5ace32d72d734bc39070
Date:   Thu Jul 26 21:10:22 2018 +0900
send queue …
=> option_data_loss_protect part2

ptarm/src/ln/ln.c, ptarm/src/ln/ln_db_lmdb.c, ptarm/src/ln/ln_misc.c, ptarm/src/ln/ln_node.c, ptarm/src/ln/ln_signer.c
fix #634 
* `ln_db_copy_channel()` でscriptpubkeyをコピーする(復元はload時に行っている）。
* scriptpubkeyのログが邪魔なので、減らす
=> recover script pubkey from basepoint

ptarmd/cmd_json.c
fix #637 
invoiceのr-fieldにpublic channelが入っているとエラーになるらしい。
`announcement_signatures`の交換が完了していないchannelだけをr-fieldに追加する。
=> add r-field only not announcement

ptarm/src/ln/ln.c
* `short_channel_id`が0の場合でも`announcement_signatures`を保存する
* `short_channel_id`が0の場合は`annoucement_signatures`送受信完了フラグを立てない
=> save announcement_signatures if short_channel_id == 0

ptarmd/cmd_json.c
切断に時間がかかるチャネルがある場合、自動接続によって切断済みのチャネルに接続してしまう
=> disable auto connect on `ptarmcli -q`

cmn/conf.c
#651 
一旦、`option_data_loss_protect`をデフォルトで無効にする。
あくまでも一旦。
=> remove option_data_loss_protect

cmn/conf.c
This reverts commit e7b14f516d20a33961adb5286d86a9eb5fc0c21f, reversing
changes made to bad145be9a96edcb7ddb609e6fe6499ec4171d6b.
=> Revert "Merge pull request #654 from nayuta-ueno/ueno/issue_651_escape"

ptarm/src/ln/ln_enc_auth.c
fix #660 
* noise handshake時のassert削除
* ACT ONEのsenderはassertを残す
* それ以外のnoise protocolもassertを残す
* MbedTLS版でも問題がなさそうであれば、assertをはずそう
=> remove assert when handshake

ptarm/include/ln.h, ptarm/src/ln/ln.c, ptarmd/lnapp.c
commitment_signedの再送対応
ただし、`update_add_htlc`に対する`update_fulfill_htlc`送信まで至っていないので、 #546 自体の解消にはならない。
それには #662 のような対策が必要である。
=> re-send commitment_signed

include/ptarmd.h, ptarm/include/ln_db_lmdb.h, ptarm/src/ln/ln_db_lmdb.c, ptarmcli/ptarmcli.c, ptarmd/ptarmd.c
`ptarmcli` でポート番号未指定の場合、カレントディレクトリに `dbptarm` があるならば、そちらを使用する。
=> ptarmcli RPC port number from DB

ptarmd/lnapp.c
sockete送信でタイムアウトは発生しないだろうと思っていたが、Raspi相手のせいかENOENTが発生することがあった。
=> send timeout

ptarm/src/ln/ln.c
Message Retransmissionテストのために、過去の`per_commitment_secret`を全部出力させるようにしていたログをコメントアウト。
Raspberry Piには荷が重すぎた。
=> reduce log

ptarm/include/ln.h, ptarm/src/ln/ln.c, ptarm/src/ln/ln_db_lmdb.c, ptarmd/monitoring.c, showdb/showdb.c
`commitment_number`と`revocation_number`から、HTLCの状態を割り出すように変更。
* 安定
* 状態1: update_add_htlc側がcommitment_signedを送信後
* 状態2: それに対してrevoke_and_ack返信後
* 状態3: 続けてcommitment_signed送信後
* 状態4(＝安定): それに対してrevoke_and_ack送信後
状態1の途中であればHTLCの追加をキャンセルし、それ以降は`commitment_signed`を再送する。
=> issue #546

ptarm/include/ln.h, ptarm/src/ln/ln.c
fix #676 
`self->fund_flag`にopen済み状態を追加。
funding状態だから、open前の状態やcloseのフラグを持つことも何らおかしくないはずだ。
=> add opened flag

ptarm/examples/Makefile, routing/routing.c
examplesのビルドが通らなかったので追加の修正。
ついでにrouting.cppも修正。
=> move all submodules to libs/(2)

ln/ln.c
fix #699 
mutual close時、funderしかDB保存しておらず、remoteのscriptPubKeyを保存できていなかった。
そのため、monitoring.cでclosing_txのチェック(vout[0]がどちらかのscriptPubKeyであること)に失敗していた。
=> save shutdown scriptpubkey

btc/btc_local.h, ln/ln_local.h, ptarmd/ptarmd.h, utl/utl_local.h, utl/utl_log.c, utl/utl_log.h
to remove log macros, explicitly define `PTARM_UTL_LOG_MACRO_DISABLED`
=> refactor log macros

ln/ln.h, ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_node.c, ptarmd/lnapp.c
fix #715
* initial_routing_syncが無効な場合はannouncement送信を擬似的に行い、全部送信したように見せかけてから接続を開始する
commit ef8d84f7d797034dfa0a47f4e6ec51fb3947d09d
Date:   Tue Aug 28 14:35:57 2018 +0900
名前整理
commit 968e2bcce29e65b3048f2beb37e80988ba6ee405
Date:   Tue Aug 28 10:37:39 2018 +0900
log
commit 6e037811fa68c6c86466a920b1753eca55084515
Date:   Tue Aug 28 10:33:46 2018 +0900
作戦変更
announcement送信処理で「ダミー」ができるようにし、起動時に全部送信したことにする
commit d0b767df9d2992642dfe3929710ca30b3cc0d63d
Date:   Tue Aug 28 01:04:43 2018 +0900
途中までやったが、中断
commit f9c1e052c0617a7059ce73358f6feff2a26b2dd7
Date:   Tue Aug 28 01:04:21 2018 +0900
log
commit …
=> fix initial_routing_sync OFF

ptarmd/cmd_json.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h
fix #665 
送金前にinvoiceのtimestamp + expiryが現在時刻を過ぎていないかチェックする(イコールはOKとする)。
=> check invoice timestamp before payment

ln/ln.c, ln/ln.h, ptarmd/lnapp.c
fix #720 
`channel_announcement`受信と`channel_update`受信におけるfunding_txのunspentチェックを削除。
おそらく、この処理が重たかったために`lnd`からの受信をさばききれず、`lnd`は送信ができないままタイムアウトしてしまっていたのではないかと思われる。
=> remove funding_tx close check

ptarmd/cmd_json.c, ptarmd/cmd_json.h, ptarmd/p2p_svr.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h
LISTENしようとしたポートが既に使われていたら、終了する。
エラーチェックはしていたが、他のスレッドが生き残っていたため終了できていなかった。
=> exit on listen port already using

ln/ln_enc_auth.c
DEVELOPER_MODEが未指定の場合にwarningが出ていた。
=> reduce warning if no DEVELOPER_MODE

ln/ln_db_lmdb.c, ln/ln_segwit_addr.c
fix #731 
複数のprivate channelがあり、複数のr-fieldを含んだinvoiceを作る場合、2番目以降がおかしなデータになっていた。
各r-fieldごとにencodeするのではなく、全部のr-fieldを作ってからencodeする必要があった。
=> fix invoice `r-field`

ln/ln.c, ln/ln.h, ln/ln_msg_normalope.c, ln/ln_onion.c, ptarmd/lnapp.c
issue #98 (part 1).
receive `update_malformed_htlc`.
* backward `update_fail_htlc` with `failure_code` and `sha256_of_onion`.
=> read update_malformed_htlc (not tested)

utl/Makefile, utl/tests/test_utl.cpp, utl/tests/testinc_args.cpp, utl/utl_args.c, utl/utl_args.h
コマンドラインオプション（argv）パース用
bitcoind形式のオプションを想定
引数あり：-name=\<arg\>
引数なし：-name
utl_arginfo_t型のスタティックなテーブルに、対応するオプションとデフォルト値、helpの文言等を定義し、そのテーブルとargv、argcを一緒にパースする。
utl_args_is_setでオプションが設定されているか確認。
引数ありの場合には、utl_args_get_string等で設定されたオプションの値やデフォルト値を取得。
=> utl: add utl_args.[ch]

utl/Makefile, utl/tests/test_utl.cpp, utl/tests/testinc_jsonrpc.cpp, utl/utl_jsonrpc.c, utl/utl_jsonrpc.h
jsonrpcのbody作成用の関数を追加
bool utl_jsonrpc_create_request(
utl_str_t *body,
const char *method,
const char *paramv[],
int paramc,
const utl_jsonrpc_param_t *non_string_params
);
上４つは説明不要であろう。
最後はparamvの要素がstringかそれ以外（bool/number/etc.）であるかを判断するためのテーブルである。
=> utl: add utl_jsonrpc.[ch]

btc/btc.h, btc/btc_ekey.c, btc/btc_keys.c
ekeyのprint APIで、key[]にでたらめな値が入っているとABORTしていた。
=> fix ekey print

Makefile, libs/Makefile
libbtc.a だけを別のところで使うとき用。
ptarmiganとは関係ない。
=> copy libbtc.a

Makefile, btc/btc.h, btc/btc_keys.c, btc/btc_local.h, btc/btc_sw.c, btc/btc_tx.c, btc/btc_util.c, ln/ln_enc_auth.c, ln/ln_misc.c, ln/ln_misc.h, ln/ln_onion.c
多くの変更が入ったかのように見えるが、行ったのは以下だけである。
* btc.hの中にあり、btc内でしか使用しないものをbtc_local.hに移動
* ついでにプレフィクスを`btcl_`に変更
* btc.hの中にあり、ln内でしか使用しないものをln_miscに移動
=> move to btc_local.h using only libbtc

btc/Makefile, btc/examples/Makefile, ln/Makefile, options.mak, ptarmcli/Makefile, ptarmd/Makefile
default option: disable gcov
cross compile時に邪魔なため
=> disable gcov coverage option

ptarmd/lnapp.c
fix buffer overflow
to_remoteがあり得ないシーンだったので目立つように文字列を変更したのだが、バッファサイズのことを忘れていた。
=> fix strcpy overflow

ln/ln.c, ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_node.c, ln/ln_node.h, ptarmd/lnapp.c, ptarmd/lnapp.h
issue #778 part1
channel data didn't match after initial_routing_sync.
* remove orphan channel except own channel
調査したところ、単独のchannel_updateが不一致の原因のように見える。
まずは、自分が持っていない単独のchannel_updateだけ削除するしくみを用意する。
=> issue #778 part1

ptarmd/btcrpc.h, ptarmd/btcrpc_bitcoind.c, ptarmd/lnapp.c
のちほどptarmcliにgetnewaddressだけを行うコマンドを追加したいがため。
=> ptarmd: change `btcrpc_getnewaddress`'s output format

ln/ln.c, ln/ln_routing.cpp, ptarmd/cmd_json.c
fix #790 
送金できないshort_channel_idがDBにあり、それと一致するチャネルはroutingから除外するようにしている。
このバグは、r-fieldを除外していなかったために発生していた。
=> skip r-field containing routeskip DB

ln/ln.c, ptarmd/monitoring.c
unilateral closeを相手が行った場合、to_remoteはP2WPKHで自分に送られる。
しかし、ptarmiganはwalletを持っていないため、bitcoindに再送金する必要がある。
今回は再送金処理が動作していなかったことに対する修正である。
=> fix unilateral close's to_remote output

btc/segwit_addr.c, btc/tests/testinc_bech32.cpp
Merged original segwit_addr.c fix
> https://github.com/sipa/bech32/commit/2b0aac650ce560fb2b2a2bebeacaa5c87d7e5938
> Fix a buffer overflow in the C reference decoder
>
> Thanks to Christian Reitter and Dr. Jochen Hoenicke for discovering this issue
> and suggesting a fix.
=> Fix a buffer overflow in the C reference decoder

ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_node.c, ln/ln_routing.cpp, ln/tests/testinc_ln.cpp, ptarmd/cmd_json.c
add `ln_db_self_search_readonly()` for readonly channel search
DBがロックすることがあったので、明示的に分けた。
=> readonly channel search

ptarmd/btcrpc_bitcoinj.c
bitcoinjの初期同期に時間がかかる。
Raspberry Pi Zeroでは想像以上に時間がかかるため、当面は30分程度で様子を見る。
=> bitcoinj ctor timeout: 30min

install/default_conf.sh, ptarmd/conf.c
default `max_htlc_value_in_flight_msat` = UINT32_MAX
follow BOLT#7
https://github.com/lightningnetwork/lightning-rfc/commit/4c12ae8a27846f47d4c837b1b1fcc9c5b7aed175
=> change `max_htlc_value_in_flight_msat` value

ln/ln.c, ln/ln.h, ptarmcli/ptarmcli.c, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/lnapp.h, ptarmd/p2p_cli.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h
`init.localfeatures.initial_routing_sync`を0に変更したため、接続要求時に`initial_routing_sync=ON`を指示できるように変更。
おそらくだが、serverとして接続されるときは`initial_routing_sync=OFF`で、clientとして接続しに行くときに指定できるのがよいのではなかろうか。
ただ、lndなどは再接続要求が比較的早いため、`ptarmd`を起動して手間取っていると相手から接続されてしまう。そういう場合は、手動で切断してから再接続する想定にしている。
内部で切断して再接続することもできるが、少なくとも今の段階ではわかりづらくなるため、やめておいた。今後の課題とする。
=> ptarmcli -c --initialroutesync

btc/btc.h, btc/btc_ekey.c, btc/btc_keys.c, btc/btc_tx.c, btc/btc_util.c, btc/examples/key_address.c, btc/tests/testinc_ekey.cpp, btc/tests/testinc_keys.cpp, btc/tests/testinc_send.cpp, ln/ln_db_lmdb.c, ln/ln_msg_anno.c, ln/ln_node.c, ptarmcli/ptarmcli.c, ptarmd/btcrpc.h, ptarmd/btcrpc_bitcoind.c, ptarmd/btcrpc_bitcoinj.c, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/ptarmd_main.c, showdb/showdb.c
DB作成後にIPアドレス/ポート番号の変更を可能とする。
* `ptarmd -p -a`未指定時
* 新規
- `port=9735`
- `addr=NONE`
* DBあり
- `port=前回`
- `addr=前回`
* `ptarmd -p指定`
- `port=指定値`
* `ptarmd -a指定`
* routing可能なアドレス... `addr=指定値`
* それ以外... `addr=前回`
=> allow change ipaddr

ln/ln.c, ln/ln_local.h, ptarmd/cmd_json.c
fix close: part1
`shutdown`交換後は`closing_signed`以外は受け付けないと考えていたときの名残を削除。
正確には、以下の条件が成立する場合をエラーと考えていた。
* `shutdown`交換後
* 受信typeが以下のいずれでもない
* `closing_signed`
* announcement系
* `ping` or `pong`
* `error`
=> fix close1

btc/btc.h, btc/btc_local.h, btc/btc_tx.c, btc/btc_util.c, btc/tests/testinc_tx.cpp
- rename `btc_valid_t` -> `btc_txvalid_t`
- rename some `BTC_TXVALID_*`
例えば`BTC_TXVALID_VERSION`などはversionが不正だという値だが、そのまま読むと「正しいバージョン」になってしまうので`BTC_TXVALID_VERSION_BAD`にした
- rename `btc_tx_create_vout` -> `btc_tx_create_spk`
- rename `btc_tx_create_vout_p2pkh` -> `btc_tx_create_spk_p2pkh`
例えば`btc_tx_add_vout`などはbtc_tx_tに対してvoutを追加するが、上記の関数は、
単純にscriptPubKeyを作成するだけなのでvoutをspkに変更した
- rename `btc_tx_set_vin_p2sh` -> `btc_tx_set_vin_p2sh_multi`
汎用的なp2shのものではなくmultisig専用なので
ほか、戻り値を返さないものを返すようにしたり
=> btc: btc_tx: refactor

btc/Makefile, btc/btc.h, btc/btc_keys.c, btc/btc_sig.c, btc/btc_sw.c, btc/btc_tx.c, btc/btc_util.c, btc/examples/tx_verify.c, btc/tests/test_main.cpp, btc/tests/testinc_keys.cpp, btc/tests/testinc_tx.cpp, ln/ln_msg_anno.c, ln/ln_node.c, ln/ln_script.c, ln/ln_signer.c, ln/ln_signer.h, ln/tests/test_main.cpp, ptarmd/wallet.c
and
rename `btc_keys_createmulti` -> `btc_keys_create_multisig`
rename `btc_tx_set_vin_p2sh_multi` -> `btc_tx_set_vin_p2sh_multisig`
=> btc: btc_tx: separate signature functions into `btc_sig.[ch]`

btc/btc_script.c, btc/btc_script.h, btc/btc_tx.c
add `_sig`
`btc_script_set_vin_p2pkh` -> `btc_script_sig_create_p2pkh`
`btc_script_set_vin_p2sh_multisig` -> `btc_script_sig_create_p2sh_multisig`
`btc_script_sign_p2pkh` -> `btc_script_sig_sign_p2pkh`
`btc_script_verify_p2pkh` -> `btc_script_sig_verify_p2pkh`
`btc_script_verify_p2pkh_spk` -> `btc_script_sig_verify_p2pkh_spk`
`btc_script_verify_p2pkh_addr` -> `btc_script_sig_verify_p2pkh_addr`
`btc_script_verify_p2sh_multisig` -> `btc_script_sig_verify_p2sh_multisig`
`btc_script_verify_p2sh_multisig_spk` -> `btc_script_sig_verify_p2sh_multisig_spk`
`btc_script_verify_p2sh_multisig_addr` -> `btc_script_sig_verify_p2sh_multisig_addr`
=> btc: btc_script: rename

btc/btc_crypto.c, btc/btc_crypto.h, btc/btc_extkey.c, btc/btc_keys.c, btc/btc_sig.c, btc/tests/testinc_keys.cpp, ln/ln_derkey.c, ln/ln_misc.c, ln/ln_node.c, ln/ln_onion.c
`btc_util_ecp_point_read_binary2` -> `btc_ecc_ecp_point_read_binary2`
`btc_util_ecp_muladd` -> `btc_ecc_ecp_muladd`
`btc_util_mul_pubkey` -> `btc_ecc_mul_pubkey`
`btcl_util_set_keypair` -> `btc_ecc_set_keypair`
=> btc: btc_crypto: rename functions

ptarmd/cmd_json.c
ノード接続がなくてもinvoice作成ができるようにする。
integration-testで失敗するので、元に戻す。
=> can create invoice if not connected

ln/ln_db_lmdb.c
skip DBが見つからない場合に、検索結果を「skipしない」にする
=> return skip_none if skip DB not exist

ln/ln.c, ln/ln_db_lmdb.c, ln/tests/Makefile, ln/tests/test_ln_proto_updatechannel.cpp
BOLT07
* if the timestamp is unreasonably far in the future:
* MAY discard the channel_update.
受信した`channel_update.timestamp`が自分の時間より1時間より進んでいる場合、DB保存しない。
=> BOLT07[channel_update] timestamp too far

ln/ln.c, ln/tests/test_ln_proto_updatefee.cpp, ptarmd/lnapp.c, ptarmd/monitoring.c
#976 関連
チャネル接続時、前回と同じ`feerate_per_kw`で再開するつもりだったが、そうなっていなかった。
それ以外の修正箇所は、予期しない値で設定されるのを防ぐためである(0の場合には無視する)。
=> fix feerate_per_kw

ln/ln.c, ptarmd/lnapp.c
fix PR #977
チャネル接続時のfeerate_per_kw初期値を前回のfeerate_per_kwと同じ値になるように変更(#977)したが、チャネル未開設の場合には0が入っていて、そのまま`open_channel`で使っていた。
=> get feerate_per_kw before `open_channel`

ptarmd/lnapp.c
fix #976 
`channel_reestablish`の後処理前に`update_fee`が作動してしまい、commitment_number / revocation_numberの判定ずれが生じていた。
初期化完了フラグを後処理後にずらすことで、それより前にcommitment_signedが必要になる動作を行わないようにする。
=> change channel initialize timing

ln/ln.c, ln/ln.h, ln/ln_db_lmdb.c, ptarmd/lnapp.c, ptarmd/lnapp.h
fix #971 
`announcement_signatures`を受信した場合、初回であれば再送する。
この場合の「初回」は、接続して初めて、と解釈している(BOLT07)。
=> reply announcement_signatures

ptarmcli/ptarmcli.c, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/lnapp.h, ptarmd/ptarmd.h
add `ptarmcli -c XXX --noinitroutesync`.
現在のデフォルト動作は`--noinitroutesync`のままにするが、変更する可能性あり(`PTARMD_ROUTESYNC_DEFAULT`)。
=> ptarmcli : add `--noinitroutesync`

ln/ln.c, ln/ln.h, ln/ln_db_lmdb.c, ptarmd/lnapp.c, ptarmd/lnapp.h
In initial_routing_sync, nodes(c-lightning, eclair, lnd) don't send `pong` against our `ping`.
But their send `pong` after initial_routing_sync at all once.
initial_routing_syncでannouncementを送信している間、彼らは`ping`受信に対して`pong`送信を行わない。
しかし、`ping`を無視しているわけではなく、全部が終わった後にまとめて送信してくる。
そのため、`ping`で送信した"`pong`に載せてくるignoredのサイズ"を保持しておき、`pong`を受信した順に比較する。
こちらとしてはinitial_routing_sync中かどうかにかかわらず`ping`を送信する必要があるが(そうしないと相手から切断される)、`ping`に対して`pong`が返ってこない場合に切断するのは難しい。
当面は60回までであれば`ping`に対する`pong`がなくても切断しない。
=> lnapp: add pong list for delay pong reply

ln/ln.c, ln/ln_msg_normalope.c, ln/ln_msg_normalope.h, ln/tests/test_ln_msg_normalope.cpp
rename `ln_update_fail_htlc_t` -> `ln_msg_update_fail_htlc_t`
refactor
`ln_msg_update_fail_htlc_write`
`ln_msg_update_fail_htlc_read`
=> ln_msg_normalope: refacotr `ln_msg_update_fail_htlc_*`

ln/ln.c, ln/ln_msg_normalope.c, ln/ln_msg_normalope.h, ln/tests/test_ln_msg_normalope.cpp
ln_msg_normalope: refactor `ln_msg_update_fail_malformed_htlc_*`
rename `ln_update_fail_malformed_htlc_t` -> `ln_msg_update_fail_malformed_htlc_t`
refactor
`ln_msg_update_fail_malformed_htlc_write`
`ln_msg_update_fail_malformed_htlc_read`
AND
ln_msg_normalope: refactor `ln_msg_update_commitment_signed_*`
rename `ln_update_commitment_signed_t` -> `ln_msg_update_commitment_signed_t`
refactor
`ln_msg_update_commitment_signed_write`
`ln_msg_update_commitment_signed_read`
=> ln_msg_normalope: refactor

ptarmd/cmd_json.c
add payment execution date/time in invoice.log
sample
```
----------- invoice -----------
payment_hash: 7f94b02aaabe6e9975ea178532d08dc06b16ebdbf608fa18067ee187692144a8
amount_msat: 800000
current blockcount: 1956
min_final_cltv_expiry: 9
timestamp: 2019-01-17T10:02:31Z
----------- route -----------
[0] 023cfc892387a8039d0aeee37b56b3f7a8630ff6a4c1d04adb4addb1cf04129ad3
short_channel_id: 1955x2x0
amount_msat: 800000
cltv_expiry: 1965
[1] 02209a5537b10a5e72e85af9ea7fc3e61122f10dcce4fd71730dc3a6dd0bd3c874
----------- end of route -----------
result(2019-01-17T10:02:37Z)=start payment
result(2019-01-17T10:02:38Z)=success
```
=> invoice log: add date/time

tests/4nodes_test/example_st4fail4c.sh
=> fix: remove unuse argument

ln/ln.c, ln/ln.h, ptarmd/lnapp.c
`update_fail_htlc`受信時、payeeからのエラー時にルート検索から除外するようにしていなかった。
当初は、routingに失敗した場合は次回以降もルートから検索できないようにしていたため、payeeがエラーを返すと二度と送信できなかったためにpayeeだけ別にしていたのかもしれない(自動で再ルーティングしていなかった時代の名残かもしれない)。
=> add skip DB among routing hop

ln/ln.c
socket接続後、noise protocol handshakeの手前でエラーになった場合、`ln_term()`呼び出しによって未設定のnoise handshake用メモリを解放しようとしてしまう。
メモリの確保は`ln_handshake_start()`で行われ、handshakeの直前に呼び出され、`malloc()`は無条件で行われている。
そしてhandshakeの終了時にエラーであっても`ln_handshake_free()`で解放されるため、ここは削除しても大丈夫なはず。
=> fix: crash if disconnect before noise handshake

ln/ln.c, ln/ln_anno.c, ln/ln_anno.h, ln/ln_msg.c, ln/ln_msg.h, ln/ln_msg_anno.c, ln/ln_msg_anno.h, ln/tests/test_ln_msg_anno.cpp, ln/tests/test_ln_msg_anno_gossip.cpp, ptarmd/Makefile, routing/Makefile, showdb/Makefile
gossip_queryのencode/decodeのみ追加。
`init.localfeatures`のgossip_queryフラグは立てていないし、送信もしていない。
=> gossip_query: create message

ln/ln_establish.c
lnd check max_htlc_value_in_flight_msat <= funding_msat recently.
funding_sat = 100000
```
error "maxValueInFlight too large: 4294967295 mSAT, max is 100000000 mSAT"
```
=> ln: max_htlc_value_in_flight_msat upper limit

ln/ln_node.c, ln/ln_node.h, ln/tests/Makefile, ln/tests/test_ln_node.cpp, ptarmcli/ptarmcli.c, ptarmd/cmd_json.c, ptarmd/conf.c, ptarmd/conf.h, ptarmd/lnapp.c, ptarmd/monitoring.c, ptarmd/p2p_svr.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h, ptarmd/ptarmd_main.c, utl/utl_net.c
カレントディレクトリにconnlist.confファイルがある場合、`ptarmd`の起動時にノード接続しにいく。
チャネルオープンなどは行わない。
現在はnode0～4まで使用する。
```
node0=028df7753f0802ec2b781ffd44da838b7b57baebe2930132411fded4399e33bf58@40.115.138.202:9735
node1=0390e7b01cefe69a76c7084acaebf13be2d95d536897f93f00faf31bcc1a41ec21@13.78.12.166:9735
node2=03a6265d05735a3092839ec48a0519a42d3e294239c154ece9b88cc1577c8f6b62@13.78.35.128:9735
```
=> ptarmd: starting node connect list

ln/ln_node.c, ln/tests/test_ln_node.cpp
localhostと接続することも多いため、IPアドレスのチェックは行わない。
IPv4のチェックまでは行う。
=>  ln_node: connlist don't check IP address routability.

ptarmd/ptarmd.c
script use current directory.
JAR use execute directory.
=> script: use current directory

ptarmcli/ptarmcli.c, ptarmd/cmd_json.c, ptarmd/lnapp.c
`ptarmcli -l1`で短い情報を出力する。
1以外は、今まで通り(文字列でも同じ)。
```
{
"result": {
"node_id": "034dc970b108e793e3217e83467e63f6cd08f44540280ca8081c90b4fbcdeaf2f0",
"node_port": 3333,
"total_local_msat": 0
}
}
```
=> ptarmcli -l : short list `-l1`

ptarmd/ptarmd_main.c
`ptarmd`が未知のoptionを付けても起動していたため、終了させる。
=> ptarmd: exit at  invalid option

ln/ln.c, ln/ln.h, ln/ln_anno.c, ln/ln_db_lmdb.c, ln/ln_msg_anno.c, ln/ln_msg_setupctl.c, ln/ln_setupctl.c, ln/ln_setupctl.h, ln/tests/Makefile, ln/tests/test_ln_anno.cpp, ln/tests/test_ln_proto_init.cpp, ptarmd/lnapp.c, ptarmd/lnapp.h, ptarmd/ptarmd.c
* gossip_queries negotiationしていない場合の対応追加
* gossip_queries系メッセージ(奇数)で何も返さない
* gossip_queries系メッセージ(偶数)はsocket切断
* `init.localfeatures`受信で、gossip_queriesの偶数bitを許容する
=> gquery: check gossip_queries negotiation

btc/btc_tx.c, utl/utl_log.h
`PTARM_UTL_LOG_MACRO_DISABLED`を定義した際にコンパイルエラーとなったため、マクロ追加。
=> log: fix PTARM_UTL_LOG_MACRO_DISABLED

ln/ln.c, ptarmd/monitoring.c, tests/4nodes_test/example_st5.sh
mutual closeでfundeeが閉じていなかった件の修正
以前は、funding_txがマイニングされているかどうかをチャネルオープンしたブロックから毎回行っていた。
が、raspberry piの場合にはその処理に時間がかかるため、前回チェックしたブロックは次回チェックしないようにした。
そして、ステータスの都合上、fundeeは2回チェックが走らないとクローズにならないようになっていたので、miningのチェックが1回しか動作しないとうまくいかなくなっていた。
まあ、クローズのステータスは見直した方が良いな。
=> fix close: close check on funding_tx is mined

ln/ln.c, ln/ln.h, ln/ln_close.c, ptarmd/lnapp.c, ptarmd/monitoring.c
#1144 の続き。
channelスレッドで、接続を切るかどうかのチェックに「close_wait」を使っていたが、あれは`shutdown`の交換以降のステータスのため、`closing_signed`が終わってないのに切断してしまうことがあった。
その修正をしていくと「close_spent」という、funding_txがSPENTされたようだ、という状態が中途半端だったので取り除き、funding_txをSPENTしたトランザクションがマイニングされたらクローズ種別を判定するようにした。
=> fix close2: remove CLOSE_SPENT

ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_db_lmdb.h, ln/ln_node.c, ln/ln_routing.cpp, ln/tests/test_ln_proto_updateaddhtlc.cpp, ptarmd/cmd_json.c, ptarmd/lnapp.c, showdb/showdb.c
DBからのchannel読み込み時、basepointでのkey復元と、funding_txの2-of-2復元を行わない関数を追加。
Raspberry Piでの速度向上を目的とする。
* 全amountの合計取得
* invoice作成のr-filed
* short_channel_idに対応するnode_id取得
keyを初めて使用する際に復元する、というやり方がよいだろうが、今回はこれで。
=> ln_db: add channel load with no key

ptarmd/lnapp.c
`error`メッセージによるログ保存は、以下の場合はevent.logに出力する。
* short_channel_idが未確定
* `error.channel_id`がオールゼロ
=> Logfile err

ptarmd/cmd_json.c, ptarmd/p2p_cli.c, ptarmd/p2p_svr.c, ptarmd/ptarmd.c, tests/4nodes_test/example_st3.sh, tests/4nodes_test/example_st_quit.sh, tools/log_filter.sh
`all_tests.sh`を実行してエラーになっている場合、以下のようなログがあった。
* JSONRPCでquitを受け取ったが、monitoringの再接続動作と重なってすぐに切断 or 相手が既にquit状態になっている
* `ping`を打ったが、相手が先にquitしている
そういうことから、切断前後を見直した。
* monitoringスレッドを先に終わらせる
* それでもタイミングによっては再接続するので、再接続エラーはlog_filter.shでスルー
* socketのaccept()待ちになっているところは、accept後に終了フラグをチェック
* announcementの完了チェックを、announcement数(9つ)とnode_announcement数(3つ)で比較する
* 以前の比較方法で問題があったわけではないが、数の方が確実な気がしている
=> fix ptarmd quit process

ln/ln_db_lmdb.c
#1155 の続き
channel loadの引き続いてkey createさせないことについては、連続動作させても影響がないようだったため、戻す。
read onlyについては現象が発生するため、ここを対処するか、できなければread onlyをなくす。
=> fix_db: no key create

ptarmd/monitoring.c
負荷軽減のため、SPVの場合のみfeerate取得をブロック高更新時のみにする(bitcoindの場合は30秒間隔のまま)。
feerateサービスにJSONを取得しに行くため、あまり頻度は高くない方がよいと思われる、というのもある。
=> Reduce getfee

ptarmd/monitoring.c
Workaround for `lightning-integration`'s timeout (outside BOLT specifications)
=> ptarmd: change the monitoring cyclic for developer mode to 20s

ptarmd/cmd_json.c, ptarmd/lnapp.c
mutual closeはestablish～normal operationの期間のみ可能なので、statusをチェックする。
ついでに、`getinfo`で常時status出力を行う。
=> check status before mutual close

ptarmd/cmd_json.c
Using bitcoinj, `ptarmcli --emptywallet` return "blockchain error".
change "wallet error".
=> emptywallet: return wallet error(bitcoinj)

ln/ln.h, ln/ln_anno.c, ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_msg_anno.c, ptarmd/lnapp.c, ptarmd/lnapp.h, showdb/showdb.c
* anno DBのkeyでshort_channel_idを使っている場合、今まではLittleEndianだったが、BigEndianに変更する。
* Gossip Queriesではshort_channel_idを昇順にすることが求められているため。
* announcementを送信済み(annoinfo DB)にする関数追加
* 未送信にする際、node_idが無くなってもkeyだけは残すようにする
* `ln_gquery_t`は、まだ準備しているだけ。
=> gquery8: anno DB key change BigEndian for sort

ln/ln_anno.c
`reply_channel_range`は`channel_announcement`を持つshort_channel_idだけにする。
=> gquery: reply_channel_range only channel_announcement

ln/ln_anno.c, ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_msg_anno.c, ptarmd/lnapp.c, ptarmd/lnapp.h
`query_short_channel_ids`受信で、該当するchannel_announcementを未送信状態にする(と、自動で送信する)。
* `query_short_channel_ids`は相手の全チャネルを要求している。
* channel_announcement系だけを未送信にしているだけで、node_announcementはまだやっていない。
* gossip_queriesは有効にしていない。
その他:
* `init`メッセージの交換が完了するまでsocket受信を強制的に止める
* gossip_queriesの判定が終わり前に相手からgossipのメッセージを受信する可能性がある
* `init`交換するまではメッセージを送信しないルールなので問題ないはず
* anno: log short_channel_id string
* lnapp: flag_recv value ENUM-->DEFINE
=> gquery10: receive query_short_channel_ids

ptarmd/lnapp.c
lnappのpolling threadでestablish以降かどうかの判定方法を変更。
以前はfunding_txidの代入有無を見ていたが、うまくいかないことがあったため。
=> lnapp: change establish check

ptarmd/lnapp.c, ptarmd/ptarmd.c
ln_recv()で失敗した場合、mutexのunlockを忘れている。
=> lnapp: forget pthread_mutex_unlock() if ln_recv() failed.

ln/ln_db_lmdb.c, ln/ln_db_lmdb.h, routing/routing.c, showdb/showdb.c
closeしたchannel DBをclosed_envに移動させていたが、サイズがいずれあふれることが分かった。
後から参照することも少ないため、channelごとにclosed_envを作り、そこに移動させる方式に変更する。
mpEnvClosedをグローバルで持たなくするため、`showdb -q`は停止する。
=> lmdb: each channel closed environment

tests/2nodes_test/example_st5.sh, tests/4nodes_test/example_st5.sh
testsのclose後に、`ptarmcli -l`のチェックを追加。
まだタイムアウトは240secでよさそう。
=> tests: st5 getinfo check

ln/ln_routing.cpp, ptarmd/lnapp.c, routing/routing.c
#1271 関連。
すぐに結果は出ないが、足して悪いことはないため、足しておく。
足すのは暫定でcltv_expiryに10block。
=> ln_route: add cltv offset(fixed 10 block)

ln/ln_setupctl.c, ln/ln_setupctl.h, ptarmd/cmd_json.c, ptarmd/lnapp.c
`error`は\0を含まないことがあるため、asciiの場合は自分で付加する。
テスト用に`DEVELOPER_MODE`でビルドした場合、JSON-RPC "DEVsend_error"を追加。
=> fix: error message data

ptarmd/lnapp.c
socket接続直後のstatus確認は、受信スレッド開始前のstatusを使用する。
そうしなかった場合、タイミングによってはコマンドによってstatusが変更されてしまうことがあった。
=> lnapp: check channel status after connection

ptarmd/lnapp.c
pong応答チェックをping送信直後に行うと必ずfalseになってしまうため、1回分のpongまではtrueで返す。
=> lnapp: pong check allow 1 pong remain

ln/ln_db_lmdb.c
forward DBでMDB_DBS_FULLが発生したため、closeを追加。
=> lmdb: forward dbi close

ptarmd/monitoring.c, ptarmd/p2p.c, ptarmd/p2p.h
=> p2p: remove `peer_conn`

ptarmd/lnapp.c, utl/utl_thread.c
ln_open_channel_sendが完了する前に、accept_channelを受信した時、"not funder"と判定されるエラーを修正
=> lnapp: fix to ensure the atomicity of `ln_open_channel_send`

Makefile, ln/ln_normalope.c
when the channel is inactove or closing
=>  ln_normalope: do not fail a forward msg if it is already registered

install/pay_fundin.py
signatureサイズを中間値で計算していたが、最大値にしてINPUTSは多めに集め、後でvsizeの調整をしても足りなくならないようにする。
=> pay_fundin.py: max signature length

install/pay_fundin.py, ptarmcli/ptarmcli.c
bitcoindでも`ptarmcli -c [node_id] -f [funding_sat],[push_msat]`形式を使用できるようにする。
内部で`python3 pay_fundin.py`を呼び出す。
=> ptarmcli: [fund]call python script

ln/ln_invoice.c, ln/ln_invoice.h, ln/ln_payment.c, ln/tests/test_ln_bech32.cpp, ptarmcli/ptarmcli.c, ptarmd/cmd_json.c
`ptarmcli --decodeinvoice`追加
* descriptionは"ptarmigan"固定のまま(cmd_json.cで指定しているので、cliで受け取るようにもできる)
* BOLT11では639文字以上の場合にはhashにするようなことが書かれている
* そんなに長い必要もないだろうし、現在は固定文字列なので、cmd_jsonは暫定で20文字チェックをしている
* `ptarmcli --addinvoice`を`ptarmcli -i`と同じように使える
* `ln_invoice_decode()`での結果は`ln_invoice_decode_free()`で解放すること
* `ptarmcli -r`でptarmcliがinvoiceデコード内容を標準出力に吐き出していたが、取りやめた。
* 送金開始時の戻り値にしてもよいかもしれない
=> decodeinvoice

ln/ln_commit_tx.c, ln/ln_commit_tx.h, ln/ln_normalope.c, ln/ln_update_info.c
due to a remote `commit_num` gap.
=> ln_normalope: resend msgs at reestablishing

ln/ln_establish.c, ptarmd/lnapp.c
after exchangeing `channel_reestablish`
=> ln_establish: resend `revoke_and_ack` immediately if necessary

ptarmd/cmd_json.c
=> cmd_json: fix to terminate an invoide string a zero

ptarmcli/ptarmcli.c
ptarmcliのpayment, invoice系コマンドにlong optionを追加(short optionはそのまま)。
他のコマンドと並べていてバランスが悪いため。
* -r = --sendpayment
* -m = --listinvoice
* -e = --removeinvoice
=> ptarmcli: add long option

ln/ln.c, ln/ln.h, ln/ln_close.c, ln/ln_close.h, ln/ln_db_lmdb.c, ln/ln_establish.c, ln/ln_normalope.c, ln/ln_update_info.c, ln/ln_update_info.h, ln/tests/test_ln_proto_updatefee.cpp, ptarmd/lnapp.c
ln_normalope: fix to follow the conditions to send closing messages
`shutdown`
after sending `commitmemt_signed` (no pending updates)
`closing_signed`
no HTLCs and no updates
=> ln_normalope: fix to follow the conditions to send closing msgs

ptarmd/conf.c, ptarmd/ptarmd_main.c
bitcoin.confに`rpcuser``rpcpassword`がない場合にptarmdは起動しないが、エラーメッセージが表示されなかった(confファイル指定も同様)。
```
fail: no rpcuser or rpcpassword[/home/ueno/.bitcoin/bitcoin.conf]
fail: wrong conf file.
```
=> ptarmd: rpcuser/rpcpassword not found error

install/pay_fundin.py
pay_fundin.pyは、bitcoindのunspentなoutpointを集めてfunding_txへのinputとなるトランザクションを作っている。
通常はそれだけでよいのだが、テスト中にregtestでfeerateを維持するために適当に送金し続けるスクリプトを動かし続けているため、pay_fundin.py実行中に送金されてunspentでなくなるということが発生した。
通常は発生しないという気もするが、ptarmd以外にもbitcoindを使うアプリが動いている可能性もあるため、inputにするoutpointは`lockunspent`で極力固めるようにする。
=> pay_fundin.py: lock input

ptarmd/btcrpc_bitcoind.c, ptarmd/monitoring.c
#1343 
1回だけだが、mutual close後、closing_txを取得し損ないcloseが完了しない事態が発生した。
再現できないため推測になるが、funding_txをoutpointに持つトランザクションを検索処理の途中でマイニングが発生して、そのブロックをスキップしたために取りこぼしたのではないか、と考えた。
対策は月並みだが、少し多めにブロックをチェックする、というもの。
=> fix issue #1343

ptarmd/cmd_json.c, ptarmd/wallet.c
`ptarmcli --paytowallet`のJSON resultを"txid"から"message"に変更。
`--paytowallet=1`のときはtxidだけを出力していたが、送金先アドレスも見せるようにする。
=> ptarmcli: paytowallet result

ptarmd/cmd_json.c, ptarmd/p2p.c
既にポートが使用中の場合に`ptarmd`を起動すると、coreを吐いて終了してしまう。
せめて、coreを吐かないようにさせる。
なお、先にc-lightningでポートを使用中にして`ptarmd`を起動すると、c-lightningがcoreを吐く。
* jsonrpc-c stop only `port_number` != 0
* `bind()`に失敗した場合は、アプリの正常終了を待たずにexit()する
他のスレッドがbind()の失敗により後に立ち上がってしまい、終了できないことがあった
=> issue #1365

ln/ln_db.h, ln/ln_db_lmdb.c
fix #1376
`ptarmcli --removeinvoice PAYMENT_HASH`後にDBのcommitを実行する。
=> commit after removeinvoice

ln/ln_db_lmdb.c
for `forward` and `payment`
`mdb_dbi_close` is not thread-safe
we do not do it because it is not necessary
=> ln_db_lmdb: fix to not close dbs

update_libs.sh
`read: Connection reset by peer`のerrorログが気になるため、read()のエラー出力を非表示にする。
=> update: jsonrpc-c

ptarmd/lnapp.c
this function takes a long time to complete?
=> lnapp: skip `check_unspent_short_channel_id`

install/pay_fundin.py
`locked_tx`にlockunspentしたtxidを記録し、エラーの場合はunlockさせる。
`sum`を`sum_amount`に変更したのは、pythonの組み込み関数でsum()があったため。
=> fundin.py: unlock after error

ln/ln_anno.c, ln/tests/test_ln_proto_updatechannel.cpp
workaround
this function is too late at `initial_routing_sync`
we will put this back when the `gossip_querry` implementation is complete
=> ln_anno: disable to verify sigs of announcements

ln/ln_normalope.c
after clear irrevocably committed updates
=> ln_normalope: fix to save channels

.gitignore, btc/btc_sig.h, ln/ln.c, ln/ln_commit_tx.c, ln/ln_commit_tx.h, ln/ln_htlc_tx.c, ln/ln_htlc_tx.h, ln/ln_normalope.c, ln/ln_normalope.h, ln/tests/test_ln.cpp, ln/tests/test_ln_htlcflag.cpp, ln/tests/test_ln_proto_acceptchannel.cpp, ln/tests/test_ln_proto_openchannel.cpp, ln/tests/test_ln_proto_updateaddhtlc.cpp, ln/tests/test_ln_proto_updatefee.cpp, ptarmd/monitoring.c
local/remote unilateral closeの修正
- HTLC outputsを直接回収するトランザクションの作成、およびそこからpreimageの摘出
- onchainのpreimageおよびtimeoutを別のチャンネルへ中継（update_fulfill/fail_htlc）
- closing中のチャネルに別のチャネルで受信したpreimageを反映させる
=> fix local/remote unilateral close

ln/ln_commit_tx.c, ln/ln_db_lmdb.c, ln/ln_derkey.c, ln/ln_establish.c, ln/ln_msg_normalope.c, ln/ln_msg_x_normalope.c, ln/ln_normalope.c, ln/ln_onion.c, ptarmd/monitoring.c, ptarmd/wallet.c, utl/utl_str.c
シークレットがログで表示されている部分を削除
`preimage`
だいたいがこれ。
final nodeはhopについては表示しても問題ないが、origin nodeは表示してはいけない。
考えるとめんどうなので、とりあえず一律表示しないようにした。
`per_commitment_secret`
これも消した。
channel_reestablishで送るピアのper_commitment_secretは消していない。
それ以外は、
ptarmd/wallet.c: なんかよくわからんがsecretが表示されていた。
utl/utl_str.c: 汎用的な関数なのでなにが表示されるかわからないのでエラー時の表示を消した。
=> remove log of secrets

ptarmcli/ptarmcli.c
=> ptarmcli: `PEER NODE_ID` -> `PEER_NODE_ID`

ln/ln_db_lmdb.h, showdb/showdb.c
`LN_DB_ROUTE_SKIP_TEMP` and `LN_DB_ROUTE_SKIP_WORK` are duplicated.
=> lmdb: fix skip value

ptarmd/cmd_json.c
fix #1441 
`sendpayment`: return error if less parameter.
=> issue #1441

ptarmapi/src/ptarmigan/ptarmigan.service.ts, ptarmd/cmd_json.c
`openchannel` returns success, but not progressing by parse error.
=> ptarmapi: fix openchannel

ptarmd/cmd_json.c
`ptarmcli --getinfo`
今までは `DEVELOPER_MODE`が有効な場合だけblockcountを返していたが、常に返すようにする。
=> ptarmcli getinfo: add `block_count`

ln/ln_db_lmdb.c
listinvoiceで表示する処理が楽になるよう、\0まで含めて保存する。
LMDBの処理単位からすると、ほとんど増加しないと思われる。
=> save BOLT11 invoice \0 for listinvoice

libs/Makefile
At 2019/05/30, boost.tar.gz fail download from dl.bintray.com.
=> boost: download from sourceforge if fail at dl.bintray.com

ln/ln_establish.c
fix: multi channel request after funding_locked.
It's happen funding status clear on `funding_locked` receiving before `funding_locked` exchanged.
=> fix: multi channel request after funding_locked

ptarmd/btcrpc_bitcoinj.c, ptarmd/jni/btcj_jni.c
bitcoinj use SLF4J to output log.
change log output destination from file to stdout.
ファイルの場合は1ファイルに格納し続けるしか方法がなく、サイズを打ち切ることができなさそうだった。
標準出力にすると、`cronolog`などで制御しやすい。
=> bitcoinj: log to stdout

.circleci/config.yml, .gitignore, tests/BTCPayServer.Lightning/LICENSE, tests/BTCPayServer.Lightning/README.md, tests/BTCPayServer.Lightning/docker-compose.yml, tests/BTCPayServer.Lightning/ptarm/Dockerfile, tests/BTCPayServer.Lightning/ptarm/docker-entrypoint.sh
Add BTCPayServer.Lightning to Ptarmigan's test.
Perform the following test using  [BTCPayServer.Lightning](https://github.com/btcapayserver/BTCPayServer.Lightning).
In order for the latest Ptarmigan to work stably on BTCPayServer.Lightning.
Test interconnection of Ptarmigan, LND, clightning, Eclair using BTCPayServer.Lightning.
Since the tests performed by each CI are largely different, We decided to divide them.
Travis CI tests Ptarmigan alone, and Circle CI tests BTCPayServer.Lightning.
=> Add BTCPayServer.Lightning.Tests

ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_version.h, ptarmd/btcrpc.h, ptarmd/btcrpc_bitcoind.c, ptarmd/btcrpc_bitcoinj.c, ptarmd/jni/btcj_jni.c, ptarmd/jni/btcj_jni.h, ptarmd/lnapp.c, ptarmd/monitoring.c, ptarmd/monitoring.h, ptarmd/tests/testinc_lnapp.cpp, ptarmd/wallet.c, showdb/showdb.c
After unilateral close, to_local, to_remote and HTLC outputs save to wallet DB.
`ptarmcli --paytowallet` pay from wallet DB to Bitcoin blockchain spending some confirmation.
But, getting confirmation from TXID is difficult for bitcoinj.
wallet DB保存する際にminingされたblock countも保存するようにし、現在のblock countからconfirmationを計算するように変更する。
ただ、これはbitcoinjのみの対応とし、bitcoindについては`getrawtransaction`からconfirmationが取得できるため現状のままとする。
DBバージョンも1つ上げる。
bitcoind版は自動的に継続、bitcoinj版はwallet DBでconfirmationを確認する必要がない場合に自動継続する。bitcoinj版でconfirmationを確認する場合は起動不可。
そのせいで実装としてはbitcoindとbitcoinjに分かれてしまうが、致し方あるまい。
=> bitcoinj: `paytowallet` need commit_tx confirmation.

ptarmd/wallet.c, tests/2nodes_test/example_st3j.sh
#1519 #1514 
SPVの対応をしていてwallet DBのunspentチェックを外していたが、少なくともbitcoind版では不具合が発生していた(#1519)。
そのため、bitcoind版について元に戻す。
=> wallet DB: check unspent

ptarmd/lnapp_cb.c
bitcoinj catches funding_tx in block download event.
If block download happen before set channel, fail detect funding_tx.
=> btcrpc: set channel before sendrawtransaction

ln/ln_db_lmdb.c
Currently annodb needs 1GB or more.
In the future, ptarmd needs to be able to keep running
if the db exceeds the upper limit.
=> ln_db_lmdb: workaround for M_ANNO_MAPSIZE

ptarmd/monitoring.c, ptarmd/wallet.c
* bitcoinjの場合、unilateral closeのcomit_tx outputに対するheightを保存するタイミングがなかったため追加
* [ptarmigan-jar](https://github.com/nayutaco/ptarmigan-jar/tree/da7c81bda795050de5be9cac180e1680af8cea6f)
=> fix: SPV unilateral close

ln/ln_anno.c, ptarmd/lnapp.c, showdb/showdb.c
受信した`announcement_signatures`のデータがおかしい場合、fail channelする。
* short_channel_id == 0
* 自分のshort_channel_id !=0 で不一致
* verify fail
* DB保存に失敗
=> (announcement_signatures) fail the channel if not correct

ptarmd/monitoring.c
`short_channel_id` is saved if getting parameter is successful.
=> monitoring: save short_channel_id

ptarmd/cmd_json.c
`ptarmcli --connaddr NODE_ID@IPADDR` use port number 9735.
=> ptarmcli --connaddr: use default port number if abbreviate

ln/ln_establish.c
start waiting funding_tx before sending `funding_signed`.
逆にしていたため、`funding_signed`送信後にminingが発生すると、funding_txの取得開始ブロックがmining後から始まってしまい、検出できなくなっていた。
=> funding_signed: wait funding_tx before sending funding_signed

install/script/addfinal.sh, ptarmapi/script/addfinal.sh, ptarmd/lnapp_cb.c
`local_msat` takes a lot of time for limited resource PC(like Raspberry Pi Zero).
final `local_msat` is noticed by `htlcchanged.sh`.
=> addfinal : remove local_msat

options.mak, tools/rpi_bj.sh
`DISABLE_PRINTFUND`を有効にするとshowdbのパラメータがいくつか出力されないため、元に戻す。
=> SPV option: not DISABLE_PRINTFUND

ptarmd/btcrpc_bitcoinj.c
getblockcountの失敗を返すようにする。
peerの取得失敗時にもgetblockcountを失敗するようにして、confirmationだけが先に進むことを防ぐ。
=> SPV getblockcnt fail

libs/Makefile
https://github.com/nayutaco/ptarmigan/pull/1510#issuecomment-506545180
python2.7 support until January 1, 2020.
https://www.python.org/dev/peps/pep-0373/
=> mbedtls: test use python3

ptarmd/cmd_json.c, ptarmd/cmd_json.h, ptarmd/lnapp_manager.c, ptarmd/lnapp_manager.h, ptarmd/p2p.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h
`ptarmd_stop`を呼び出しても、ptarmdが終了しない。
`jrpc_server_stop()`呼び出しによって`jrpc_server_run()`から抜ける予定であったが、抜けないようだった。
JSON-RPC経由で呼び出すと抜けるようだったので、そうする。
* JSONRPC "EXIT"を追加
* `jrpc_server_stop()`を呼び出す
* ptarmdから"EXIT"を呼ぶ `cmd_json_exit()`を追加
* `ptarmd_stop()`からは`cmd_json_exit()`を呼び出す
=> fix ptarmd_stop()

ln/ln_db_lmdb.c
annoinfo DBにcursorでnode_idを保存する際の判定が逆になっていた。
#1594
=> fix add annoinfo

ptarmd/btcrpc_bitcoind.c
JSON-RPC(`listunspent`) return BTC amount by string.
jansson library use `strtod()`  to convert double value to integer.
After convert, the value need round off.
```
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <inttypes.h>
#define VALUES		"20999991.99978481"
int main(void)
{
double val = strtod(VALUES, NULL);
printf("%20.8lf\n", val);
printf("  %20.10lf\n", val);
// NG "2099999199978480"
printf("%" PRIu64 "\n", (uint64_t)(val * (uint64_t)100000000));
// OK "2099999199978481"
printf("%" PRIu64 "\n", (uint64_t)(val * (uint64_t)100000000 + 0.5));
return 0;
}
```
=> bitcoind: round JSON amount value

ptarmd/lnapp.c, ptarmd/lnapp.h, ptarmd/lnapp_cb.c
[BOLT2 Message Retranmission](https://github.com/lightningnetwork/lightning-rfc/blob/8555709811e6b2326f80dc479021b161e850bf03/02-peer-protocol.md#requirements-14) describe " MUST send `funding_locked`", but do not describe "MUST receive `funding_locked`".
So, do not wait for receiving `funding_locked` on Normal Operation status.
=> not wait funding_locked on Normal Operation status

ln/ln_establish.c, ln/ln_normalope.c, ln/ln_setupctl.h, ptarmd/lnapp.c, ptarmd/monitoring.c
再接続時、channel_reestablishより前にfunding_lockedを受信した場合、unilateral closeしていた。
channel_reestablish ==> funding_lockedと想定していたため、順番が違えばfail channelするからちょうど良かったのだが、BOLTとしてはどちらの順でも受け入れるべきと判断。
channel_reestablish送受信済みフラグをfunding_lockedと共通化していたため、funding_locked受信→channel_reestablish送信の時点で「channel_reestablish送受信済み」の処理を行ってしまい、next値の判定がうまくいっていなかった。
=> receive funding_locked before channel_reestablish

btc/btc_script.c, btc/btc_script.h
OP_PUSHDATA3 is not part of bitcoin script. Only OP_PUSHDATA1, OP_PUSHDATA2 and OP_PUSHDATA4 are valid. 
https://github.com/bitcoin/bitcoin/blob/master/src/script/script.h#L59-L61
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nayutaco/ptarmigan/1654)
=> Correct name of upcode 0x4e to OP_PUSHDATA4
