nayutaco/ptarmigan

include/ucoind.h, install/example_st4.sh, ucoincli/ucoincli.c, ucoind/inc/lnapp.h, ucoind/lnapp.c, ucoind/ucoind.c
Payee cannot select payment channel(only payer).
=> preimage: lnapp --> ucoind

CHANGELOG.md, README.md, cmn/jsonrpc.c, docs/clightning_test_ja.md, include/jsonrpc.h, install/example_st3.sh, install/fund-in2.sh, routing/routing.cpp, ucoin/include/ln.h, ucoin/include/ln_err.h, ucoin/src/inc/ln/ln_local.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_derkey.c, ucoin/src/ln/ln_misc.c, ucoin/src/ln/ln_msg_establish.c, ucoin/src/ln/ln_onion.c, ucoin/src/ln/ln_print.c, ucoin/src/ln/ln_script.c, ucoin/src/ucoin_tx.c, ucoin/src/ucoin_util.c, ucoind/inc/lnapp.h, ucoind/lnapp.c, ucoind/ucoind.c
=> c-lightning対面送金

cmn/conf.c, routing/routing.cpp, ucoin/src/ln/ln.c, ucoin/src/ln/ln_misc.c, ucoin/src/ln/ln_print.c, ucoind/lnapp.c, ucoind/ucoind.c
* payment test
* ptarmigan --> clightning --> clightning
* ptarmigan <-- clightning <-- clightning
=> c-lightning hop test

CHANGELOG.md, install/default_conf.sh, ucoin/include/ln.h, ucoin/src/ln/ln.c, ucoind/lnapp.c
send `channel_update` after reconnect parameter changed.
=> send channel_update after reconnect

CHANGELOG.md, ucoin/include/ln.h, ucoin/include/ln_db.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_node.c, ucoin/src/ln/ln_print.c, ucoind/lnapp.c, ucoind/p2p_cli.c
=> Save normalope

ucoin/gtests/testinc_ln_bolt3_b.cpp, ucoin/gtests/testinc_ln_bolt3_c.cpp, ucoin/gtests/testinc_ln_bolt3_d.cpp, ucoin/gtests/testinc_ln_bolt4.cpp, ucoin/include/ln.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_msg_anno.c, ucoin/src/ln/ln_msg_close.c, ucoin/src/ln/ln_msg_establish.c, ucoin/src/ln/ln_msg_normalope.c, ucoin/src/ln/ln_msg_setupctl.c, ucoind/lnapp.c
=> original URL

cmn/conf.c, ucoin/include/ln.h, ucoin/src/inc/ln/ln_enc_auth.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_enc_auth.c, ucoin/src/ln/ln_msg_setupctl.c, ucoind/lnapp.c, ucoind/ucoind.c
=> reduce warning

routing/routing.cpp, showdb/showdb.c, ucoin/include/ln_db_lmdb.h, ucoin/src/ln/ln_db_lmdb.c, ucoind/inc/p2p_cli.h, ucoind/p2p_cli.c, ucoind/ucoind.c
=> codefix db

install/example_st2.sh, install/script/closed.sh, install/script/established.sh, install/script/fail.sh, install/script/forward.sh, install/script/fulfill.sh, install/script/htlcchanged.sh, install/script/payment.sh, ucoin/include/ln.h, ucoind/lnapp.c
* [add] established, closed
* [chg] echo JSON output
=> add send event

docs/clightning_test_ja.md, install/create_knownpeer.sh, showdb/showdb.c, ucoin/src/ln/ln.c, ucoind/lnapp.c
今のc-lightningとの接続テスト
* #45 
* #46
=> clightning connect

routing/routing.cpp, ucoind/lnapp.c
JSON-RPC "getinfo" adds some items.
=> Show status

ucoin/src/inc/ln/ln_local.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_msg_establish.c
init localfeatures & open_channel channel_flags
=> init flag & open_channel flag

ucoin/include/ln.h, ucoin/src/inc/ln/ln_local.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_msg_setupctl.c, ucoind/lnapp.c
If features only odd bits, the features can ignore.
(#45 is that)
=> init: features

cmn/conf.c, include/ucoind.h, ucoin/include/ln.h, ucoind/inc/lnapp.h, ucoind/lnapp.c, ucoind/ucoind.c
#29 
おそらく、 `min_final_cltv_expiry` はCLTVのオフセット的な使い方になると思われる。
=> add min_final_cltv_expiry

cmn/jsonrpc.c, include/jsonrpc.h, include/ucoind.h, install/script/closed.sh, install/script/established.sh, install/script/fail.sh, install/script/forward.sh, install/script/fulfill.sh, install/script/htlcchanged.sh, install/script/payment.sh, showdb/showdb.c, ucoin/include/ln.h, ucoin/include/ln_db.h, ucoin/include/ucoin.h, ucoin/src/inc/ln/ln_local.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_node.c, ucoin/src/ln/ln_script.c, ucoin/src/ucoin_sw.c, ucoincli/ucoincli.c, ucoind/inc/lnapp.h, ucoind/lnapp.c, ucoind/ucoind.c
=> Watch ugly

.vscode/c_cpp_properties.json
=> vscode setting

install/2/example_st1.sh, install/4/example_st1.sh, install/script/closed.sh, install/script/established.sh, install/script/fail.sh, install/script/forward.sh, install/script/fulfill.sh, install/script/htlcchanged.sh, install/script/payment.sh, ucoind/lnapp.c
=> Testjson date

ucoin/src/ln/ln.c
https://github.com/lightningnetwork/lightning-rfc/pull/298
=> BOLT spec change : close_tx version 2

ucoin/src/ln/ln_msg_establish.c
=> funding_satoshis less than 2^24

ucoin/gtests/Makefile, ucoin/gtests/testinc_ln_bolt3_b.cpp, ucoin/gtests/testinc_ln_bolt3_c.cpp, ucoin/gtests/testinc_ln_bolt3_c2.cpp, ucoin/gtests/testinc_send.cpp, ucoin/include/ln_db.h, ucoin/src/inc/ln/ln_local.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ucoin_util.c, ucoind/monitoring.c
=> ucoin gtests

ucoin/src/ln/ln.c, ucoin/src/ln/ln_msg_anno.c, ucoin/src/ln/ln_msg_establish.c, ucoind/lnapp.c
わからない `channel_update` は無視するものらしい
=> Ignore channel_update

.vscode/c_cpp_properties.json, ucoin/src/inc/ln/ln_local.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_msg_anno.c, ucoin/src/ln/ln_script.c
`revocationkey` を remoteとして扱っているが、localにしたほうがよいのではないか、と考えて変更しようとした。
が、いろいろ考えた末に変更しないことにした。
ここでは、引数名の変更やログ出力の追加だけ行っている。
=> Remote revokey

include/ucoind.h, ucoin/include/ln.h, ucoin/include/ln_db.h, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_msg_anno.c, ucoin/src/ln/ln_node.c, ucoincli/ucoincli.c, ucoind/cmd_json.c, ucoind/inc/cmd_json.h, ucoind/inc/lnapp.h, ucoind/inc/p2p_cli.h, ucoind/lnapp.c, ucoind/monitoring.c, ucoind/p2p_cli.c, ucoind/p2p_svr.c, ucoind/ucoind.c
チャネルを閉じていない状態で相手ノードと未接続の場合、接続要求を行う。
JSON-RPCコマンドを自分(localhostの自ノード待ち受けポート)に送信する
=> Auto reconnect

.gitmodules, ucoin/libs/Makefile
=> fix makefile

docs/clightning_test_ja.md
=> document update

docs/routing_ja.md, docs/ucoincli_ja.md, ucoincli/ucoincli.c
=> JSON-RPC document

include/misc.h, include/ucoind.h, install/2/example_st3.sh, install/2/example_st5.sh, install/4/example_st3.sh, install/4/example_st5.sh, ucoin/include/ln.h, ucoin/src/inc/ucoin_local.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_node.c, ucoind/cmd_json.c, ucoind/inc/lnapp.h, ucoind/inc/p2p_cli.h, ucoind/lnapp.c, ucoind/p2p_cli.c, ucoind/p2p_svr.c
You can funding after connect.
=> Separate connect and fund

docs/clightning_test_ja.md
=> fix document

ucoind/lnapp.c
以前、write()で送信したいサイズと送信したサイズに違いが発生したことがあった。
おそらく、送信データが多くなってバッファにたまってしまったのではないか。
=> write()を複数回に分けられるようにする

ucoin/include/ln.h, ucoin/src/ln/ln_msg_anno.c
=> LN_NODEDESC_NULL --> LN_NODEDESC_NONE

docs/clightning_testnet_ja.md, install/create_knownpeer2.sh
=> doc: testnet

cmn/misc.c, include/misc.h, include/ucoind.h, routing/routing.cpp, ucoin/include/ln.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoind/cmd_json.c, ucoind/lnapp.c, ucoind/monitoring.c, ucoind/p2p_cli.c, ucoind/p2p_svr.c, ucoind/ucoind.c
=> JSON-RPC : add "routepay"

routing/routing.cpp
=> fix stderr output

ucoin/src/ln/ln.c
=> ping size 16bit

include/ucoind.h, ucoin/src/ln/ln_db_lmdb.c, ucoincli/ucoincli.c, ucoind/cmd_json.c
よくわからないが、routepayコマンドに失敗していた。
invoiceの状態がおかしかったのか？
はっきりしなかったため、invoice削除コマンドを追加した。
=> Fix routepay

install/script/closed.sh, install/script/connected.sh, install/script/established.sh, install/script/fail.sh, install/script/forward.sh, install/script/fulfill.sh, install/script/htlcchanged.sh, install/script/payment.sh, ucoind/lnapp.c
if payment event happens, scripts will be called.
=> Event scripts

install/script/htlcchanged.sh
=> our_msat.txt update

docs/howtopay_starblocks_ja.md
I added the doc/howtopay_starblocks_ja.md
=> add howto pay doc

docs/howtopay_starblocks_ja.md
=> change title

docs/howtopay_starblocks_ja.md
=> Doc update

ucoin/include/ln_db.h, ucoin/src/ln/ln_db_lmdb.c, ucoind/cmd_json.c
=> compile warning

ucoin/include/ln.h
add comment
変数のcommit_numは"next_commitment_number"に相当する
=> add comment

cmn/jsonrpc.c, install/4nodes/example_st3.sh, install/4nodes/example_st5.sh, routing/routing.cpp, showdb/showdb.c, ucoin/include/ln_db.h, ucoin/src/inc/ln/ln_local.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_msg_anno.c, ucoin/src/ln/ln_node.c, ucoin/src/ln/ln_print.c, ucoind/lnapp.c
reduce node log and command log
=> Reduce log

ucoin/src/ln/ln.c, ucoin/src/ln/ln_node.c
=> change log

.gitignore, Makefile, cmn/misc.c, include/misc.h, routing/routing.cpp, showdb/showdb.c, ucoin/include/ln.h, ucoin/include/ln_db.h, ucoin/include/ln_db_lmdb.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_misc.c, ucoin/src/ln/ln_msg_anno.c, ucoin/src/ln/ln_node.c, ucoin/src/ln/ln_print.c, ucoin/src/ln/ln_script.c, ucoind/Makefile, ucoind/cmd_json.c, ucoind/inc/lnapp.h, ucoind/lnapp.c, ucoind/monitoring.c
=> Each annodb

ucoincli/ucoincli.c
JSON-RPCで`final_min_cltv_expiry`を追加できるようにしておく
=> cltv offset

README.md, docs/bolt_compat_ja.md, docs/clightning_test_ja.md, docs/routing_ja.md, docs/showdb_ja.md, docs/ucoincli_ja.md, docs/ucoind_ja.md, update_libs.sh
update libraries and documents
=> update libs and docs

README.md, ucoin/include/ln_err.h, ucoind/lnapp.c
BOLT#4のONION failure reasonを文字列表示する(last error)
ucoind自体はまだfailure resonに対応していない。
=> Show onion error

cmn/btcrpc.c, include/btcrpc.h, ucoincli/Makefile, ucoind/Makefile, ucoind/cmd_json.c, ucoind/lnapp.c, ucoind/monitoring.c, ucoind/ucoind.c
=> jsonrpc --> btcrpc

install/script/established.sh, install/script/htlcchanged.sh, ucoin/src/ln/ln_msg_setupctl.c, ucoind/monitoring.c
=> Reduce log warn

libs/Makefile
ucoind allow only localhost RPC
=> jsonrpc_c only localhost

install/script/error.sh, ucoind/lnapp.c
=> error script calling

docs/ucoincli_ja.md, ucoincli/ucoincli.c
`ucoincli`のポート番号を省略した場合は 9736とする
=> Omit port9736

ucoin/src/ln/ln.c
#99 update_fee受信だけ
動作確認できていないが、このチェックだけを待っていられないので反映させる
=> receivce update_fee

install/script/error.sh
=> $err_str --> $3

docs/howtopay_starblocks_ja.md
=> no node.conf

install/2nodes_test/example_st2.sh, install/2nodes_test/example_st3.sh, install/2nodes_test/example_st4r.sh, install/4nodes_test/example_st2.sh, install/4nodes_test/example_st3.sh, install/4nodes_test/example_st4r.sh, ucoind/ucoind.c
peer.confに、alias名を付加したファイル名を付ける
=> set peer.conf name

ucoind/monitoring.c
funding済みのpeerに接続する時間をランダムにする。
効果があるか分からない。
=> random connect time

ucoind/ucoind.c
=> ucoind help

ucoin/src/ln/ln.c
=> init_routing_sync=1

docs/clightning_testnet_ja.md, ucoincli/ucoincli.c, ucoind/lnapp.c
ucoincliのJSONコマンド出力をやめる
その他、コメント修正など。
=> revice ucoincli

ucoin/libs/Makefile
=> fix incpath

docs/testnet_4nodes_ja.md
=> 4nodes tests

ucoin/include/ln_db.h, ucoin/include/ln_db_lmdb.h, ucoin/src/ln/ln_db_lmdb.c
DB: revoked transaction HTLC type追加
=> Add db revtype

showdb/showdb.c, ucoin/include/ln_db_lmdb.h, ucoin/src/ln/ln_db_lmdb.c
=> Load db ss

docs/README.md, docs/testnet_2nodes_clightning.md, docs/testnet_2nodes_eclair.md, docs/testnet_2nodes_lnd.md
The usage document is translated in English.
=> English docs

README.md, docs/README.md, docs/testnet_2nodes_clightning.md, docs/testnet_2nodes_clightning_ja.md, docs/testnet_2nodes_eclair.md, docs/testnet_2nodes_eclair_ja.md, docs/testnet_2nodes_lnd.md, docs/testnet_4nodes_ja.md
=> add: bitcoind v0.15.x

docs/README.md, docs/howtopay_starblocks.md
add how to pay starblocks (english)
=> add 1 howto file

README.md
=> thunder bird

docs/routing.md, docs/showdb.md, routing/routing.cpp, showdb/showdb.c, ucoin/include/ln_db_lmdb.h, ucoin/src/ln/ln_db_lmdb.c
show q : show closed self info
全部のselfを残しているわけではない
=> show closed self info

ucoincli/ucoincli.c, ucoind/cmd_json.c
activate: ucoincli -c <NODE_ID>
NG : `ucoincli -c <NODE_ID>` only
OK : `ucoincli -c <NODE_ID> <other option>`
=> activate: ucoincli -c <NODE_ID>

ucoind/cmd_json.c
BOLT#11形式としてmakefileのNETKINDを使用する
=> BOLT#11 invoice mainnet/testnet

cmn/btcrpc.c, cmn/misc.c, include/misc.h, ucoin/README.md, ucoin/include/ucoin.h, ucoin/src/ln/ln.c, ucoin/src/ucoin_keys.c, ucoin/src/ucoin_util.c, ucoincli/ucoincli.c, ucoind/cmd_json.c
fix #253 
fix #279 
* ucoin: segwitのnative設定を `ucoin_init()` 以降変更させない
* 16進数文字列-->バイナリ変換のデータ長変更(uint16_t --> uint32_t)
=> Fix 253, 279

showdb/showdb.c, ucoin/src/ln/ln_print.c
`showdb l` : show active channel's node_id list
=> showdb list channel

routing/routing.cpp, showdb/showdb.c, ucoin/src/ln/ln_msg_anno.c
* `channel_announcement`が存在しない`channel_update`は破棄する
* `short_channel_id==0`のannouncementは破棄する
=> Routing orphan channel

routing/routing.cpp
=> fix short_channel_id compare

ucoin/src/ln/ln.c
fix #286
commitment_numberの初期値を1とする
=> initialize commitment_number to 1

ucoin/src/ln/ln.c
unilateral closeのstorage_indexも考慮が必要
=> storage_index for unilateral close before funding_locked

routing/routing.cpp, showdb/showdb.c, ucoin/include/ln.h, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_node.c, ucoind/lnapp.c
ln_self_tは5KB程度あるため、mallocで確保する
=> ln_self_t instance malloc

.gitignore, ucoin/include/ucoin.h, ucoin/src/ucoin_tx.c
=> debug: check signing function

CHANGELOG.md, cmn/conf.c, cmn/misc.c, docs/ucoincli.md, include/misc.h, include/ucoind.h, ucoincli/ucoincli.c, ucoind/inc/lnapp.h, ucoind/lnapp.c, ucoind/p2p_cli.c, ucoind/p2p_svr.c, ucoind/ucoind.c
* allow `ucoincli -c <node_id>@<ipaddr>:<port>`
* output `connection.log`
=> Conn format

ucoind/cmd_json.c, ucoind/inc/lnapp.h, ucoind/lnapp.c, ucoind/p2p_cli.c, ucoind/p2p_svr.c
* `ucoincli -l`
* add role: "server" / "client"
* add status: "wait_connection"
=> Getinfo format

ucoincli/ucoincli.c
=> enable `ucoincli -X`

cmn/btcrpc.c, showdb/showdb.c, ucoin/include/ln.h, ucoin/include/ln_db_lmdb.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_print.c, ucoin/src/ln/ln_signer.c, ucoind/inc/lnapp.h, ucoind/lnapp.c
#308 の修正対応をしたつもりだが、テストを繰り返すにはregtest対応がいる。
そのため、一度mergeする。
=> fix 308 prepare

.gitmodules, README.md, routing/Makefile, showdb/Makefile, ucoin/.gitmodules, ucoin/Makefile, ucoin/include/segwit_addr.h, ucoin/libs/Makefile, ucoin/src/bech32/README.md, ucoin/src/bech32/segwit_addr.c, ucoin/src/bech32/tests.c, ucoincli/Makefile, ucoind/Makefile, update_libs.sh
=> Include bech32

.gitmodules, CHANGELOG.md, README.md, routing/Makefile, showdb/Makefile, showdb/showdb.c, ucoin/.gitmodules, ucoin/Makefile, ucoin/include/ln.h, ucoin/include/segwit_addr.h, ucoin/libs/Makefile, ucoin/src/bech32/README.md, ucoin/src/bech32/segwit_addr.c, ucoin/src/bech32/tests.c, ucoin/src/ln/ln.c, ucoin/src/ln/ln_msg_anno.c, ucoin/src/ln/ln_msg_setupctl.c, ucoincli/Makefile, ucoincli/ucoincli.c, ucoind/Makefile, ucoind/cmd_json.c, ucoind/lnapp.c, update_libs.sh
* bech32ライブラリを取り込む
* 修正が多い上に、ucoinとの関係が強くなりすぎてしまったため、一体化する
* fix #319 
* channel_announcement前のchannel_update受信に対応
* channel_update送信は行っていない(対応すべきか？)
* fix #318 
* node_announcementにaddrtypeがNONEは含めない
* fix #302 , fix #313 
* 受信の順番を見るようにしたが、確認はしていない
* fix #308 
* これより前に対応したはず
=> orphan channel_update recv

ucoin/include/ln.h, ucoin/src/ln/ln.c, ucoind/cmd_json.c, ucoind/lnapp.c
fix closing_tx verify
#324 関連の予定だったが、そちらは片付いていない。
=> Fix mutual close

showdb/showdb.c, tests/2nodes_test/example_st4fail3.sh, tests/2nodes_test/example_st4fail4a.sh, tests/2nodes_test/example_st4fail4b.sh, tests/4nodes_test/example_st4fail1.sh, tests/4nodes_test/example_st4fail2.sh, tests/4nodes_test/example_st4fail3.sh, tests/4nodes_test/example_st4fail4a.sh, tests/4nodes_test/example_st4fail4b.sh, ucoin/include/ln.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c
=> refactor commit_tx

ucoin/src/ln/ln.c
fix #333 
funderが`closing_signed`を送信する
=> funder sends first closing_signed

ucoin/include/ln_db.h, ucoin/src/ln/ln_db_lmdb.c, ucoind/ucoind.c
ucoind -x
DBを消すが、node情報は残しておきたい。
=> add: erase current DB

cmn/misc.c, include/misc.h, include/ucoind.h, ucoind/lnapp.c, ucoind/monitoring.c
eventをファイル保存する。
* establish開始
* establish完了
* mutual close開始
* mutual close完了
* unilateral close開始(自分から)
* revoked transaction close開始(相手から)
* close完了
* errorメッセージ受信
=> Event file

ucoin/include/ln.h, ucoind/lnapp.c, ucoind/monitoring.c
* funder/fundee
* shutdown
* funding_tx vout spent
=> add event log

showdb/showdb.c, ucoin/include/ln.h, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_msg_anno.c, ucoind/ucoind.c
=> fix alias length

docs/routing.md, include/ucoind.h, install/script/fail.sh, ucoin/include/ln.h, ucoin/include/ln_err.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoind/inc/lnapp.h, ucoind/lnapp.c, ucoind/ucoind.c
invoice amount_msatの2倍を超えるとエラー
=> Overpay twice

.vscode/c_cpp_properties.json, ucoin/gtests/testinc_ln_bolt3_c.cpp, ucoin/gtests/testinc_ln_bolt4.cpp, ucoin/gtests/testinc_tx.cpp
=> fix gtests

routing/routing.cpp, showdb/showdb.c, ucoin/gtests/testinc_buf.cpp, ucoin/gtests/testinc_ln_bolt3_b.cpp, ucoin/gtests/testinc_ln_bolt3_c.cpp, ucoin/gtests/testinc_ln_bolt3_c2.cpp, ucoin/gtests/testinc_ln_bolt4.cpp, ucoin/gtests/testinc_ln_bolt8.cpp, ucoin/gtests/testinc_ln_misc.cpp, ucoin/gtests/testinc_segwit.cpp, ucoin/gtests/testinc_send.cpp, ucoin/gtests/testinc_tx.cpp, ucoin/include/ucoin.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_node.c, ucoin/src/ln/ln_onion.c, ucoin/src/ln/ln_script.c, ucoin/src/ln/ln_signer.c, ucoin/src/ucoin_tx.c, ucoin/src/ucoin_util.c, ucoind/inc/lnapp.h, ucoind/lnapp.c
ucoin_buf_init() --> UCOIN_BUF_INIT
=> ucoin_buf_init macro

cmn/btcrpc.c, ucoin/gtests/testinc_ln_bolt3_b.cpp, ucoin/gtests/testinc_ln_bolt3_c.cpp, ucoin/include/ucoin.h, ucoin/src/ln/ln.c, ucoin/src/ucoin_tx.c, ucoind/monitoring.c
ucoin_tx_init --> UCOIN_TX_INIT macro
=> ucoin_tx_init macro

ucoind/cmd_json.c
ucoincli -m でBOLT11 invoiceも表示する
=> `ucoincli -m` shows BOLT11 invoice

ucoin/include/ln.h, ucoin/src/bech32/segwit_addr.c, ucoin/src/bech32/tests.c, ucoin/src/ln/ln_node.c, ucoin/src/ucoin_sw.c, ucoin/src/ucoin_tx.c, ucoincli/ucoincli.c, ucoind/cmd_json.c, ucoind/lnapp.c, ucoind/monitoring.c
=> Total amount

ucoind/cmd_json.c
fix #397
cltv_expiryにブロック高足し忘れ
=> add block height

update_libs.sh
* lmdb: 0.9.21 --> 0.9.22
* MbedTLS: 2.8.0 --> 2.9.0
=> libs update

ucoincli/ucoincli.c
=> show ucoincli error

ucoin/include/ln.h, ucoin/src/inc/ln/ln_script.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_script.c, ucoincli/ucoincli.c, ucoind/cmd_json.c, ucoind/inc/lnapp.h, ucoind/inc/monitoring.h, ucoind/lnapp.c, ucoind/monitoring.c
`update_fee` message(fix #99)
* check `bitcoind estimatesmartfee 6` per 30second
* if `estimatefee / 4` != `feerate_per_kw`, send `update_fee`.
=> add: update_fee

cmn/btcrpc.c, include/ucoind.h, showdb/showdb.c, ucoin/include/ln.h, ucoin/include/ln_db_lmdb.h, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_msg_anno.c, ucoin/src/ln/ln_msg_setupctl.c, ucoin/src/ln/ln_script.c, ucoincli/ucoincli.c, ucoind/cmd_json.c, ucoind/inc/lnapp.h, ucoind/lnapp.c, ucoind/monitoring.c, ucoind/ucoind.c
* fix mutex unlock
* revice source code ;)
=> fix: update_fee

ucoin/src/bech32/segwit_addr.c
=> fix bolt11

include/ucoind.h, routing/routing_main.c, ucoin/include/ln.h, ucoin/include/ln_err.h, ucoin/src/routing/ln_routing.cpp, ucoincli/ucoincli.c, ucoind/cmd_json.c, ucoind/p2p_cli.c, ucoind/ucoind.c
=> routing error output

ucoincli/ucoincli.c
前回の送金で「一時的に使用できないルート(channel)」と見なした経路を削除せずに送金を開始するオプションを追加('-R')。
既存の'-r'は削除している。
=> ucoincli: '-R: keep prev skip channel

ucoin/src/ln/ln.c
localfeatures: through odd bit
=> through odd bit

ucoin/src/ln/ln_db_lmdb.c
=> fix: chanel_announcement info

ucoind/inc/lnapp.h, ucoind/lnapp.c
channel_updateの展開時、channel_announcementがないchannel_updateを展開しないようする処理を修正
=> fix channel_update broadcast

ucoin/src/ln/ln.c, ucoind/lnapp.c
* channel_announcement受信時に該当するfunding_txが閉じられていた場合、何もしない
* channel_update受信時に該当するfunding_txが閉じられていた場合、何もしない
* channel_announcement/update展開時にチェックして、closeしていたらDB削除
=> fix closed channel on receive

ucoind/lnapp.c
=> fix PR#428

cmn/misc.c, ucoin/include/ln_db.h, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_node.c, ucoind/lnapp.c, ucoind/monitoring.c
=> arrange event log

ucoind/lnapp.c
=> fix read() error

Makefile, common.mak, routing/Makefile, showdb/Makefile, ucoin/Makefile, ucoincli/Makefile, ucoind/Makefile
=> revise makefile

ucoin/include/ucoin.h
=> remove sign log

cmn/btcrpc.c, cmn/misc.c, include/ucoind.h, ucoin/include/ucoin.h, ucoin/src/inc/ucoin_local.h, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ucoin_util.c, ucoincli/ucoincli.c, ucoind/cmd_json.c, ucoind/lnapp.c, ucoind/monitoring.c, ucoind/p2p_cli.c, ucoind/ucoind.c
=> ucoin_misc --> ucoin_util

ucoin/src/ln/ln_db_lmdb.c
=> fix db log

docs/routing.md, docs/showdb.md, routing/routing_main.c, showdb/showdb.c, ucoin/include/ln_db_lmdb.h, ucoin/src/ln/ln_db_lmdb.c, ucoind/ucoind.c
=> DB: enable set db path

ucoin/Makefile, ucoincli/Makefile, ucoind/Makefile
fix #442 
$(notdir)が無かったため、パスがあわなかった。
#445 で加えた $(abspath)は効果が無いため削除。
=> fix dependency

include/ucoind.h, ucoind/inc/lnapp.h, ucoind/lnapp.c, ucoind/p2p_cli.c, ucoind/p2p_svr.c
=> remove daemoncmd_t

include/ucoind.h, ucoind/inc/lnapp.h, ucoind/inc/monitoring.h, ucoind/inc/p2p_cli.h, ucoind/p2p_cli.c
ヘッダをextern "C"で囲む。
p2p_cli_start()をboolにしたのは、おまけ。
=> add extern "C"

tests/2nodes_test/example_st3.sh, tests/4nodes_test/example_st3.sh
=> fix showdb param

showdb/showdb.c
=> showdb: show help

ucoin/include/ucoin.h, ucoin/src/inc/ucoin_local.h, ucoin/src/ucoin_util.c
=> remove `zlog` string

docs/ucoincli.md, docs/ucoind.md, ucoin/include/ln_db.h, ucoin/src/ln/ln_db_lmdb.c, ucoincli/ucoincli.c, ucoind/cmd_json.c, ucoind/inc/cmd_json.h, ucoind/lnapp.c
* `add amount_msat`追加
* JSON-RPCの `cltv_offset`削除
=> change DB/JSON-RPC parameter for retry

cmn/btcrpc.c
=> buffer size

ucoin/src/inc/ucoin_local.h
=> fix NO DEBUG LOG

include/misc.h, ucoind/cmd_json.c, ucoind/inc/cmd_json.h, ucoind/inc/lnapp.h, ucoind/inc/monitoring.h
=> trim trail space

ucoind/cmd_json.c, ucoind/inc/cmd_json.h, ucoind/lnapp.c
=> divide pay API

cmn/misc.c, include/misc.h, install/script/connected.sh, ucoind/cmd_json.c, ucoind/inc/cmd_json.h, ucoind/lnapp.c, ucoind/monitoring.c
* misc_sendjson()移動 
* JSON-RPC: "connect" API
=> Revise json

cmn/btcrpc.c, include/misc.h
fix #488 
固定サイズでJSONを受信していたが、サイズが足りなくなったらrealloc()するように変更。
=> realloc if buffer over

showdb/showdb.c
=> showdb: DBが開けなくても止めない

ucoin/examples/tx_create.c
native P2WPKH --> native P2WPKH
=> ucoin example

cmn/btcrpc.c, include/btcrpc.h
=> revise btcrpc

cmn/btcrpc.c, ucoin/include/ln.h, ucoin/src/inc/ln/ln_enc_auth.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/ln/ln_enc_auth.c, ucoin/src/ln/ln_node.c, ucoind/lnapp.c
valgrindによるメモリリークチェックを反映。
他にもあるが、問題が大きいため先にPRする。
=> valgrind check

cmn/btcrpc.c, ucoin/src/ln/ln_node.c
PR #504 : btcrpc 戻り値修正
PR #515 : ln_node メモリ解放修正
=> fix: flag and memory

docs/ucoind.md, ucoin/include/ln_db.h, ucoin/include/ucoin.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoin/src/log/ulog.c, ucoin/src/ucoin_util.c, ucoind/lnapp.c, ucoind/ucoind.c
* 2週間以上前のchannelをprune(受信時はDB保存しない)
=> prune channel_update

ucoin/include/ucoin.h, ucoin/src/log/ulog.c, ucoin/src/ucoin_util.c
=> change type

include/ucoind.h, ucoin/include/ulog.h, ucoin/src/inc/ucoin_local.h, ucoin/src/log/ulog.c, ucoin/src/ucoin_tx.c
ログに関数名を出力させる。
実装方法には再考の余地ありだ。
```
06/13 08:14:38(84396)[src/ln/ln.c:3101:recv_channel_update][LIB]older channel: not save(13c0b50000700001): 04/26 16:19:37
06/13 08:14:38(84396)[src/ln/ln.c:3136:recv_channel_update][LIB]fail: channel_update
```
=> log: add funcname

showdb/showdb.c, ucoin/include/ln.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoind/cmd_json.c, ucoind/lnapp.c
fix #525
`update_add_htlc`に対する`commitment_signed`を受信しないまま再接続した場合、署名失敗でunilateral closeができなくなっていた。
ただ、再接続に関する理解がこれで正しいのかはわかっていないため、再検討する必要あり。
----
commit d50f7f805771c88a83de03cc5a90895e77e961cd
Date:   Fri Jun 15 08:30:07 2018 +0000
offered HTLC amount come back when HTLC cleaning
init作成時にcommitment_signed受信していないHTLCがあれば消している。
その際、offered HTLCであればour_msatから減らしているので、戻す。
commit 4f72f12c4ce5365b8a31f033e28a31c5c09fdeb2
Merge: 84438e7 5031a1f
Date:   Fri Jun 15 06:34:59 2018 +0000
Merge remote-tracking branch 'origin/fix540_cast' into work/fix_525
commit 84438e77f1429f14d275a489ee223b01a3f0a583
Merge: 29c112f 507199b
Date:   Fri Jun 15 04:38:56 2018 +0000
Merge remote-tracking branch …
=> fail receive commitment_signed 

tests/2nodes_test/example_st4fail3.sh, tests/2nodes_test/example_st4fail4a.sh, tests/2nodes_test/example_st4fail4b.sh, tests/4nodes_test/example_st4fail1.sh, tests/4nodes_test/example_st4fail2.sh, tests/4nodes_test/example_st4fail3.sh, tests/4nodes_test/example_st4fail4a.sh, tests/4nodes_test/example_st4fail4b.sh
`showdb -d`はdbucoinを指定しなくてよくなった
=> fix showdb parameter

ucoind/lnapp.c
=> `ucoincli -g` : JSON title

ucoin/include/ln.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_db_lmdb.c, ucoind/Makefile, ucoind/btcrpc_bitcoind.c, ucoind/inc/btcrpc.h, ucoind/lnapp.c, ucoind/monitoring.c
* bitcoind以外のnodeでも対応できるようにbtcrpcのインターフェース変更案1
* contain fix #559
=> change btcrpc interface - part 1

ucoin/src/ln/ln_db_lmdb.c
`showdb -q`で出力する項目を追加
* our_msat
* their_msat
* commitment number
=> `showdb -q` add items

ucoin/src/ln/ln.c, ucoin/src/ucoin_tx.c, ucoind/btcrpc_bitcoind.c, ucoind/inc/btcrpc.h, ucoind/lnapp.c, ucoind/monitoring.c, ucoind/ucoind.c
* get genesis block
* check unspent
* check outpoint
=> change btcrpc interface - part 2

cmn/conf.c, docs/ucoincli.md, include/ucoind.h, ucoincli/ucoincli.c, ucoind/cmd_json.c, ucoind/lnapp.c
fix #557
commit 558bdb5158d6c36f5cbd9a930f900445451cd17c
Date:   Wed Jun 27 10:01:34 2018 +0900
fund.conf: skip unknown option
commit b30f220301d461db7d00bb7fea1a269652074bde
Date:   Wed Jun 27 00:01:21 2018 +0900
fix #557
fund-inの署名アドレスは不要
fundingにsignaddrは不要
=> remove signaddr from fund.conf

tests/2nodes_test/example_st4fail4a.sh, tests/2nodes_test/example_st4fail4b.sh, tests/4nodes_test/example_st4fail4a.sh, tests/4nodes_test/example_st4fail4b.sh, ucoincli/ucoincli.c
fix #533 
ついでに、`setfeerate`もlong optのみにしておく
=> `ucoincli -d` --> `ucoincli --debug`

docs/testnet_2nodes_clightning.md, docs/testnet_2nodes_clightning_ja.md, docs/testnet_2nodes_eclair.md, docs/testnet_2nodes_eclair_ja.md, docs/testnet_2nodes_lnd.md, docs/testnet_2nodes_lnd_ja.md, docs/testnet_4nodes.md, docs/testnet_4nodes_ja.md, install/script/connected.sh, showdb/showdb.c
fix #453 
`showdb`でハイフン無しのオプションを削除。
=> remove no hyphen option

ucoin/src/ln/ln.c
奇数ならエラーでもOK、と解釈した。
BOLT#0の用語も参照のこと。
https://github.com/lightningnetwork/lightning-rfc/blob/master/01-messaging.md#lightning-message-format
=> BOLT#1: ok to be odd rule

ucoin/gtests/test_ucoin.cpp, ucoin/src/ln/ln.c, ucoin/src/log/ulog.c
* `ucoin/gtests`にulog追加
* warning対応
=> fix gtests and warning

routing/Makefile, showdb/Makefile, ucoin/Makefile, ucoin/include/ulog.h, ucoincli/Makefile
developer modeではverboseが出るようにした。
=> set log mode in developer mode

ucoind/lnapp.c
close中フラグが立っているときのclose要求はエラーにする
=> check already close

ucoin/include/ln.h, ucoin/src/ln/ln.c, ucoin/src/ln/ln_node.c, ucoind/lnapp.c
=> notify announcement DB update

ucoin/src/ln/ln.c
announcement_signatures送信時にもLN_CB_UPDATE_ANNODBをコールバック
=> callback announcement

ucoin/examples/key_address.c, ucoin/examples/tx_create.c
=> Ucoin examples

ucoin/include/ln.h, ucoin/src/ln/ln.c, ucoind/btcrpc_bitcoind.c, ucoind/inc/btcrpc.h, ucoind/lnapp.c
short_channel_id確定の時点でblock hashを保存する
=> bitcoin interface part7

ptarmd/btcrpc_bitcoind.c, ptarmd/inc/btcrpc.h, ptarmd/ptarmd.c
bitcoindのバージョンをチェックできるようにした。
今のところ、150000(M_MIN_BITCOIND_VERSION)以上ならOK。
=> check bitcoind version

install/README.md
=> install doc

ptarm/src/ln/ln.c, ptarmd/lnapp.c
相手から`commitment_signed`を再送された場合に対応する。
[BOLT02](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#requirements-14)
* if  `next_local_commitment_number` is equal to the commitment number of the last   `commitment_signed` message the receiving node has sent:
* MUST reuse the same commitment number for its next `commitment_signed`.
=> receive re-sent commitment_signed

.gitmodules, ptarm/.gitmodules, ptarm/README.md, ptarm/examples/Makefile, ptarm/gtests/Makefile, ptarm/libs/Makefile, ptarm/src/ln/ln_enc_auth.c, ptarm/src/ln/ln_onion.c, ptarmcli/Makefile, ptarmd/Makefile, routing/Makefile, showdb/Makefile, update_libs.sh
MbedTLSで置き換えたChaCha20-Poly1305でエラーが出ることがあるので、一旦libsodiumに戻す
=> use sodium

.gitmodules, ptarm/.gitmodules, ptarm/README.md, ptarm/examples/Makefile, ptarm/gtests/Makefile, ptarm/gtests/testinc_ln_bolt8.cpp, ptarm/include/ln.h, ptarm/libs/Makefile, ptarm/src/inc/ln/ln_enc_auth.h, ptarm/src/ln/ln.c, ptarm/src/ln/ln_enc_auth.c, ptarm/src/ln/ln_onion.c, ptarmcli/Makefile, ptarmd/Makefile, routing/Makefile, showdb/Makefile, update_libs.sh
fix #648 
* ChaCha20/Poly1305 APIの使い方修正
* libsodium削除
=> fix MbedTLS usage

ptarm/src/ln/ln.c, ptarm/src/ln/ln_signer.c
maybe fix #651 
* `my_current_per_commitment_point`は現在の`per_commitment_point`なので、再計算する
=> fix send option_data_loss_protect

ptarm/src/ln/ln_db_lmdb.c, ptarm/src/ln/ln_node.c, ptarmd/ptarmd.c
=> issue #655

showdb/showdb.c
=> fix showdb -v

ln/ln.c, ln/ln.h, ln/ln_msg_normalope.c, ptarmd/lnapp.c, ptarmd/ptarmd.h
#662 対応　その1
* cnl_add_htlc[].flagのCOMIMTフラグをcommitment_signed送受信フラグに変更
* offered HTLC時間切れ追加(unilateral closeする)
* fulfill折り返しはまだできない
=> issue #662 part1

install/script/established.sh, install/script/fail.sh, install/script/forward.sh, install/script/fulfill.sh, install/script/htlcchanged.sh, install/script/payment.sh
=> rm -f j.json

ptarmcli/ptarmcli.c, ptarmd/cmd_json.c
fix #666 
* mutual close: `ptarmcli -x`
* unilateral close: `ptarmcli -xforce`
=> ptarmcli: unilateral close option

ptarmd/ptarmd.c
=> signal catch

ln/ln_enc_auth.c
When DEVELOPER_MODE is on and $LIGHTNINGKEYLOGFILE environment variable set, ptarmigan now dumps keys to encrypt/decrypt messages.
For more specific information, [read this](https://github.com/nayutaco/lightning-dissector/blob/master/CONTRIBUTING.md#by-using-key-dump-file).
=> Support lightning-dissector

ln/ln.c, ln/ln.h, ln/ln_onion.c, ptarmd/cmd_json.c, ptarmd/lnapp.c
fix #223 
テストはできていないが、BOLT4のonionエラーにほぼ対応した。
=> support almost onion error

.gitignore, .gitmodules, .travis.yml, README.md, libs/Makefile, ln/Makefile, ln/ln_routing.cpp, options.mak, ptarmd/Makefile, routing/Makefile, showdb/Makefile, update_libs.sh
* enable cross compile
* `GNU_PREFIX` in `option.mk`
これをマージすると、元に戻すのがひどく大変なので、ご注意を。
あと、ローカルでいろいろビルドするようになるのでビルド時間が長くなります。
=> add GNU prefix

utl/tests/testinc_args.cpp, utl/tests/testinc_str.cpp, utl/utl_args.c, utl/utl_args.h, utl/utl_str.c
helpメッセージ用文字列取得API
utl_str_appendへの修正もあったりする
=> utl: add utl_args_get_help_messages

ptarmd/Makefile, ptarmd/lnapp.c, ptarmd/lnapp.h, ptarmd/ptarmd.c, ptarmd/ptarmd.h, ptarmd/ptarmd_main.c
separate `main()` for create `libptarm`.
=> separate ptarmd.c and main()

.travis.yml
=> mail notification test

.travis.yml, jni/README.md, options.mak
=> default: executable ptarmd

btc/btc.c, btc/btc.h
=> fix comment

.travis.yml, libs/mbedtls_config/config-ptarm.h, update_libs.sh
=> MbedTLS v2.13.1

btc/btc.h, btc/btc_ekey.c
no password only
ptarmiganでは使用していない。
PR #762 もよろしゅう 🙏
=> mnemonic --> seed

btc/btc.h, btc/btc_ekey.c
convert mnemonic to 64byte seed
ptarmiganでは使わない
=> ekey: mnemonic to seed

btc/btc.h, btc/btc_ekey.c
HD wallet BIP44 format
ptarmiganでは使っていない
=> ekey: generate BIP44

btc/btc.h, btc/btc_ekey.c, btc/tests/testinc_ekey.cpp
BIP49 key derive
ptarmiganでは使っていない
=> ekey: BIP49

btc/btc_util.c, ln/ln_db_lmdb.c
起動時にDB関係で失敗してもユーザに理由がほぼ分からないので、もう少し親切にした。
=> DB: print init err to output stderr

ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_misc.c, ptarmd/lnapp.c, ptarmd/monitoring.c, ptarmd/ptarmd_lib.c, ptarmd/ptarmd_main.c, showdb/showdb.c
fix #778 
* announcement検索後の処理修正
* 1回のrebroadcasting数を変更(だいたい1秒で10チャネル程度)
* announcementの枝刈り修正
=> fix announce rebroadcasting

btc/examples/Makefile, btc/examples/key_address.c, btc/examples/tx_create.c, btc/examples/tx_print.c, btc/examples/tx_verify.c, utl/utl_log.h
=> fix btc examples

docs/ptarm_event_script_ja.md
=> add event script document(Japanese)

btc/btc.h, btc/btc_sw.c, btc/btc_tx.c, btc/btc_util.c, btc/tests/testinc_segwit.cpp, ln/ln.c, ln/ln.h, ln/ln_script.c, ln/ln_signer.c, ln/tests/testinc_ln_bolt3_c.cpp, ptarmcli/ptarmcli.c, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/monitoring.c, ptarmd/p2p_svr.c, ptarmd/ptarmd.c
issue #791 
* btc_tx_is_valid()
* check transaction before calculate signature hash
* check funding_satoshis
* debug: calculate funding_tx fee
=> add transaction check

ln/ln.c, ln/tests/testinc_ln.cpp
=> fix HTLC check for test

ln/ln.c, ln/ln.h, ln/ln_db_lmdb.c, ln/ln_script.h, ln/tests/test_main.cpp, ln/tests/testinc_ln.cpp, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/monitoring.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h, showdb/showdb.c, tests/4nodes_test/example_st4fail4a.sh, tests/4nodes_test/example_st4fail4b.sh, tests/4nodes_test/example_st4fail4c.sh
#662 part3
HTLCの追加/削除をシーケンスではなく状態で行う。
* HTLC状態フラグ変更
* HTLC状態フラグによってNormal Operation操作を行う
* `revoke_and_ack`キューおよび関連処理を削除
=> issue #662 part3

ln/ln.c
=> reduce htlc final log

ptarmd/cmd_json.c, ptarmd/ptarmd.h
=> save payer invoice logfile

ln/ln.c, ln/ln.h, ln/ln_db_lmdb.c, ln/tests/testinc_ln.cpp
=> revise htlc flag

btc/btc_tx.c, ln/ln.c, ln/ln.h, ln/ln_db_lmdb.c, ln/ln_local.h, ln/ln_routing.cpp, ptarmcli/ptarmcli.c, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/monitoring.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h, ptarmd/tests/testinc_lnapp.cpp
=> Closing monitor

ln/ln_msg_anno.c, ln/ln_msg_close.c, ln/ln_msg_normalope.c, ln/ln_msg_setupctl.c
=>  allow larger packet

install/pay_fundin.sh
=> bitcoind >= 0.16

ln/ln.c, ln/ln.h, ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_derkey.c, ln/ln_derkey.h, ln/ln_node.c, ln/tests/testinc_ln_bolt3_d.cpp, ptarmd/lnapp.c, ptarmd/lnapp.h, ptarmd/monitoring.c, showdb/showdb.c
* check exist short_channel_id from ANNO DB
* DB conflict
* increase ANNO DB max size
* DB flood
* add environment check(only db debug mode)
* save last channel connect peer address and reconnection
commit e164188d24ec1039b2a91cf90c7f980db806d0cc
Date:   Tue Oct 30 20:30:19 2018 +0900
mmap size for Raspberry Pi
commit d390b05eb3ad986486f25bd627cd85f9a049b209
Date:   Tue Oct 30 18:13:36 2018 +0900
showdb: -w funding_tx
commit 71d81f5dfe13970cd48fa2bffed1a4b3b2ef8cd0
Date:   Tue Oct 30 13:26:11 2018 +0900
ln_db_self_chk_mynode()を使わない
commit 2e106ee39fb9eef01350493a20a0e34656ef9b9a
Date:   Tue Oct 30 12:33:36 2018 +0900
dbg: show pong …
=> revice DB code

ptarmd/lnapp.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h, ptarmd/ptarmd_main.c
event logをカレントディレクトリから`logs`フォルダに移動
=> event log: change event log directory

ln/ln.c, ln/ln.h, ln/ln_db_lmdb.c, ln/ln_local.h, ln/ln_routing.cpp, ln/tests/testinc_ln.cpp, ptarmd/btcrpc_bitcoind.c, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/monitoring.c, ptarmd/ptarmd_lib.c, ptarmd/ptarmd_main.c, routing/routing.c, showdb/showdb.c
`ln_` + `対象` + `_` + `動詞` `()` のイメージ
=> change API name

ln/ln_db_lmdb.c
execute DB compaction if less remaining page.
but NOT TESTED !!
=> db compaction: no test

btc/btc_keys.c, btc/btc_tx.c, ptarmd/btcrpc.h, ptarmd/btcrpc_bitcoind.c, ptarmd/lnapp.c, ptarmd/monitoring.c, ptarmd/tests/testinc_lnapp.cpp
* write error: write poll() == 0 
* bitcoind: get confirm return bool value
* WIF only compressed pubkey
=> revise code

install/script/started.sh, ptarmd/lnapp.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h, ptarmd/tests/testinc_lnapp.cpp
=> add startup event script

btc/Makefile, docs/build_for_spv.md, ln/Makefile, options.mak, ptarmcli/Makefile, ptarmcli/ptarmcli.c, ptarmd/Makefile, ptarmd/btcrpc.h, ptarmd/btcrpc_bitcoinj.c, ptarmd/cmd_json.c, ptarmd/jni/btcj_jni.c, ptarmd/jni/btcj_jni.h, routing/Makefile, showdb/Makefile, utl/Makefile
send all amount from bitcoinj wallet to one's address.
(only `USE_SPV=1`)
=> send all amount from bitcoinj wallet

ln/ln_node.c
Don't delete "notification information" at startup
=> delete annoinfo only initial_routing_sync=ON

ln/ln.c, ln/ln.h, ptarmd/lnapp.c, ptarmd/ptarmd.c, showdb/showdb.c
human readable `short_channel_id`
fix #853 
https://github.com/lightningnetwork/lightning-rfc/blob/20524d4109b6e50a7b3b54fb68086540f968d921/07-routing-gossip.md#rationale-1
=> human readable short_channel_id

ptarmd/btcrpc_bitcoinj.c
=> fix `ptarmcli-q` for SPV

ptarmd/btcrpc_bitcoinj.c, ptarmd/jni/btcj_jni.c, ptarmd/jni/btcj_jni.h
Java APIで`Sha256Hash`を使っている箇所を`byte[]`に変更する。
=> [spv]change Sha256Hash to byte[]

ptarmd/cmd_json.c
=> log: short_channel_id string

ln/ln_msg_anno.c, ptarmd/btcrpc.h, ptarmd/btcrpc_bitcoinj.c, ptarmd/jni/btcj_jni.c, ptarmd/jni/btcj_jni.h, ptarmd/monitoring.c
* fix check monitoring status
commit d6ede5163f2709aacfae4d354084df459b8f3455
Date:   Fri Dec 14 16:35:54 2018 +0900
fix monitoring status
commit 4e374a1a1383816a0bfd797bf77bb5dd8d67d854
Date:   Thu Dec 13 20:37:03 2018 +0900
mutual closeがうまくいかなくなった
=> [SPV]delete channel from bitcoinj

ln/ln.c, ln/ln.h, ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_routing.cpp, ptarmcli/ptarmcli.c, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/wallet.c
SPV unilateral close修正　その1
* status保存タイミング修正
* ptarmcli help修正
* ptarmcli -Wエラー出力
=> spv_fix_unilateral1

showdb/showdb.c
* show wallet db information
* JSON key: space-->under score
=> show more wallet DB info

ptarmd/btcrpc_bitcoinj.c
=> SPV: utl_misc_is_all_zero()

btc/Makefile, btc/btc_keys.c, btc/btc_segwit_addr.c, btc/btc_segwit_addr.h, btc/btc_tx.c, btc/btc_util.c, btc/segwit_addr.c, btc/segwit_addr.h, btc/tests/test_main.cpp, btc/tests/testinc_segwit_addr.cpp, ln/ln_segwit_addr.c, ln/ln_signer.c, ln/tests/test_main.cpp
more precise input values, especially buffer length check
=> btc: add btc_segwit_addr.[ch]

ln/ln.c, ln/ln.h, ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_routing.cpp, ptarmd/lnapp.c, ptarmd/monitoring.c, showdb/showdb.c
fix unilateral close: part3
* merge self->status & self->close_type
* update DB version: 29
=> unilateral3

utl/Makefile, utl/tests/test_utl.cpp, utl/tests/testinc_int.cpp, utl/utl_int.c, utl/utl_int.h
big/little endianのバイナリ列をpack/unpackする
=> utl: add `utl_int`

ln/ln.c, ln/ln.h, ln/ln_msg_setupctl.c, ptarmd/lnapp.c, ptarmd/p2p_cli.c, ptarmd/p2p_svr.c
call setChannel() after channel_reestablish exchange
=> sync error

install/script/htlcchanged.sh, ln/ln.c, ln/ln.h, ln/ln_err.h, ln/ln_routing.cpp, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/lnapp.h, ptarmd/ptarmd.c, ptarmd/ptarmd.h, routing/routing.c
nice `event.log` about payment
=> log routing result

btc/btc.h, btc/btc_tx.c, btc/btc_util.c, btc/examples/tx_create.c, btc/tests/testinc_segwit.cpp, btc/tests/testinc_send.cpp, btc/tests/testinc_tx.cpp, ln/ln.c, ln/ln_db_lmdb.c, ln/tests/testinc_ln_bolt3_b.cpp, ln/tests/testinc_ln_bolt3_c.cpp, ptarmd/lnapp.c, ptarmd/monitoring.c, ptarmd/wallet.c
rename `btc_tx_create` -> `btc_tx_write`
refactor `btc_tx_sighash`
change the order of the params of `btc_tx_sighash`
the top is `btc_tx_t`
=> btc: btc_tx: refactor

btc/btc.h, btc/btc_tx.c, btc/tests/testinc_send.cpp, btc/tests/testinc_tx.cpp, ln/ln.c, ln/tests/testinc_ln_bolt3_b.cpp, ln/tests/testinc_ln_bolt3_c.cpp, ptarmd/monitoring.c
=> refactor `btc_tx`

btc/btc_keys.c, btc/btc_script.c, btc/btc_script.h, btc/btc_sw.c, btc/btc_tx.c, btc/btc_util.c, btc/tests/testinc_segwit.cpp, ln/ln.c, ln/ln_script.c, ln/ln_signer.c, ptarmd/wallet.c
`btc_script_pk_*` -> `btc_scriptpk_*`
`btc_script_sig_*` -> `btc_scriptsig_*`
`btc_script_code_*` -> `btc_scriptcode_*`
=> btc: btc_script: rename

btc/btc_script.c, btc/btc_script.h, btc/btc_sw.c, btc/btc_sw.h, ln/ln.c, ln/ln_db.h, ln/ln_script.c
change params of `btc_scriptsig_create_p2sh_p2wsh`
add `btc_scriptsig_create_p2wsh`
=> btc: btc_script: refactor

.gitignore, ln/Makefile, ln/ln.c, ln/ln_comtx.c, ln/ln_comtx.h, ln/ln_db_lmdb.c, ln/tests/Makefile, ln/tests/test_ln.cpp, ln/tests/test_main.cpp, ln/tests/testinc_ln_bolt3_c.cpp, showdb/showdb.c, utl/utl_dbg.c
* check `channel_reserve_satoshis` and `dust_limit_satoshis` at `open_channel / accept_channel` received
* separate commit_tx creation from `ln.c`
=> check channel_reserve_satoshis and dust_limit_satoshis

.travis.yml, Makefile, btc/tests/Makefile, docs/build_for_spv.md, ln/ln.c, ln/ln.h, ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_local.h, ln/tests/Makefile, ln/tests/test_ln.cpp, options.mak, ptarmcli/ptarmcli.c, ptarmd/Makefile, ptarmd/btcrpc.h, ptarmd/cmd_json.c, ptarmd/conf.c, ptarmd/lnapp.c, ptarmd/monitoring.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h, ptarmd/ptarmd_main.c, ptarmd/tests/Makefile, ptarmd/tests/testinc_lnapp.cpp, ptarmd/wallet.c, showdb/showdb.c
* `USE_BITCOIND`
* `USE_BITCOINJ`
なるべくifdefを減らしたいが、実装が足りないのでそのまま。
=> change `USE_SPV` --> `USE_xxx`

ln/ln.c, ln/ln.h, ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_script.h, ln/tests/testinc_ln_bolt3_c.cpp, utl/utl_misc.c, utl/utl_misc.h
static inlineでヘッダに実装していたものをソースファイルに移動。
組み込み向けという感じでもなくなってきたので、最適化はコンパイラに任せよう。
=> header implementation --> source

ptarmd/btcrpc_bitcoind.c
fix #955
JSON-RPC接続をしたままにしておくと、bitcoindが30秒で切断するようだった。
そのため、毎回切断する。
`TIME_WAIT`は16以上にならなかったので、 #440 のようなことにはならないと思う。
=> disconnect after curl_easy_perform()

ptarmcli/ptarmcli.c, ptarmd/btcrpc_bitcoind.c, ptarmd/cmd_json.c, ptarmd/wallet.c, ptarmd/wallet.h
* ptarmcli -W  ==> ptarmcli --paytowallet
* fix buffer size for btcrpc
=> `paytowallet` require option to broadcast

ln/ln.c, ln/ln.h, ln/tests/Makefile, ln/tests/test_ln.cpp, ln/tests/test_ln_updatefee.cpp, ptarmd/lnapp.c
=> check update_fee

ln/ln.c, ln/ln.h, ln/tests/test_ln_updatefee.cpp, ptarmd/btcrpc_bitcoinj.c, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/lnapp.h, ptarmd/monitoring.c, ptarmd/monitoring.h, ptarmd/ptarmd.c, ptarmd/ptarmd.h, ptarmd/tests/testinc_lnapp.cpp
=> send update_fee

CHANGELOG.md, ln/ln.c, ln/ln.h, ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_local.h, ptarmcli/ptarmcli.c, ptarmd/btcrpc.h, ptarmd/btcrpc_bitcoind.c, ptarmd/btcrpc_bitcoinj.c, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/monitoring.c, ptarmd/p2p_svr.c, ptarmd/ptarmd.c, ptarmd/tests/testinc_lnapp.cpp, showdb/showdb.c
DBで`USE_BITCOIND`と`USE_BITCOINJ`の差違をなくす。
* DB version: -29 --> -30
=> Lmdb integrate

showdb/showdb.c
`showdb` : change output for debug
* short_channel_id: with 64bit value
* revocation_number: null if not received
=> showdb: change output

ln/ln.c
check callback function before call
=> ln: check callback function

ln/ln.c, ln/ln.h, ln/ln_msg_anno.c, ln/ln_msg_anno.h, ln/ln_msg_establish.c, ln/ln_msg_normalope.c, ln/ln_node.c, ln/ln_print.c, showdb/showdb.c
メッセージのシリアライズ/デシリアライズの方法を一貫させたい。
その一貫。
create -> writeに変えた。
=> ln:ln_msg_*: refactor

.gitignore, ln/ln.c, ln/ln.h, ln/ln_msg_establish.c, ln/ln_msg_establish.h, ln/ln_msg_setupctl.c, ln/tests/test_ln_htlcflag.cpp, ln/tests/test_ln_proto_acceptchannel.cpp, ln/tests/test_ln_proto_openchannel.cpp, ln/tests/test_ln_proto_updateaddhtlc.cpp
rename `ln_open_channel_t` -> `ln_msg_open_channel_t`
refactor
`ln_msg_open_channel_write`
`ln_msg_open_channel_read`
=>  ln_msg_establish: refacotr `ln_msg_open_channel_*`

ln/ln.c, ln/ln.h, ln/ln_msg_establish.c, ln/ln_msg_establish.h, ln/tests/test_ln.cpp, ln/tests/test_ln_htlcflag.cpp, ln/tests/test_ln_proto_acceptchannel.cpp, ln/tests/test_ln_proto_openchannel.cpp, ln/tests/test_ln_proto_updateaddhtlc.cpp
rename `ln_accept_channel_t` -> `ln_msg_accept_channel_t`
refactor
`ln_msg_accept_channel_write`
`ln_msg_accept_channel_read`
=> ln_msg_establish: refacotr `ln_msg_accept_channel_*`

ln/ln.c, ln/ln.h, ln/ln_msg_establish.c, ln/ln_msg_establish.h, ln/tests/test_ln.cpp, ln/tests/test_ln_htlcflag.cpp, ln/tests/test_ln_proto_acceptchannel.cpp, ln/tests/test_ln_proto_openchannel.cpp, ln/tests/test_ln_proto_updateaddhtlc.cpp
rename `ln_funding_created_t` -> `ln_msg_funding_created_t`
refactor
`ln_msg_funding_created_write`
`ln_msg_funding_created_read`
=> ln_msg_establish: refacotr `ln_msg_funding_created_*`

ln/ln.c, ln/ln_msg_establish.c, ln/ln_msg_establish.h
rename `ln_channel_reestablish_t` -> `ln_msg_channel_reestablish_t`
refactor
`ln_msg_channel_reestablish_write`
`ln_msg_channel_reestablish_read`
=> ln_msg_establish: refacotr `ln_msg_channel_reestablish_*`

tests/4nodes_test/all_test.sh, tests/4nodes_test/example_st_conn.sh
add reconnect test
切断前のテストで送金失敗情報がDBに書き込まれているので、それもクリアする。
=> all_test.sh : add reconnect

ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/lnapp.h, ptarmd/ptarmd.c, ptarmd/ptarmd.h
check pong_list before JSON-RPC command
* send `ping` after `init`
* if pong_list contains unreceived pong, not send JSON-RPC command to ptarmigan
* `open_channel`
* `update_add_htlc` (funder)
* `shutdown`
=> check ping/pong before JSON-RPC command

ln/ln.c, ln/ln_msg_normalope.c, ln/ln_msg_normalope.h, ln/tests/test_ln_msg_normalope.cpp, ln/tests/test_ln_proto_updatefee.cpp
rename `ln_revoke_and_ack_t` -> `ln_msg_revoke_and_ack_t`
refactor
`ln_msg_revoke_and_ack_write`
`ln_msg_revoke_and_ack_read`
AND
rename `ln_update_fee_t` -> `ln_msg_update_fee_t`
refactor
`ln_msg_update_fee_write`
`ln_msg_update_fee_read`
=> ln_msg_normalope: refactor --- end

ln/ln.c, ln/ln.h, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h, ptarmd/tests/testinc_lnapp.cpp, tests/4nodes_test/example_st4fail1b.sh, tests/4nodes_test/example_st4fail4c.sh
* check pong list before channel transfer
* fail channel if backwinding fail
=> check payment forward and result backward

ln/ln.c, ln/ln.h, ln/ln_msg_anno.c, ln/ln_msg_anno.h, ln/ln_print.c, ln/tests/test_ln_msg_anno.cpp, ln/tests/test_ln_proto_updatechannel.cpp, showdb/showdb.c
rename `ln_channel_announcement_t` -> `ln_msg_channel_announcement_t`
refactor
`ln_msg_channel_announcement_write`
`ln_msg_channel_announcement_read`
=> ln_msg_anno: refactor `ln_msg_channel_announcement_*`

ptarmd/lnapp.c
自分のchannelの場合は、2週間以上経過していてもDB削除しない。
=> keep own channel_update

ptarmd/lnapp.c
#1022 の修正不足
* payeeがエラーを返す場合は、次に転送するチャネルではないので、転送されてきたチャネルを除外する
* temporaryと付いていないエラーはすべてpermanently扱いにしていたが、permanentlyではないエラーをtemporary扱いとする
* `channel_disabled`はpermanently扱いで良いだろう
=> fix: payee return error

ln/ln.c, ln/ln.h, ln/ln_anno.c, ln/ln_db_lmdb.c, ln/ln_derkey.c, ln/ln_derkey.h, ln/ln_establish.c, ln/ln_msg_establish.c, ln/ln_normalope.c, ln/ln_signer.c, ln/ln_signer.h, ln/tests/testinc_ln_bolt3_d.cpp, ptarmd/monitoring.c, showdb/showdb.c
=> ln_derkey: include `peer_storage_index` in `ln_derkey_storage_t`

ln/ln.c, ln/ln.h, ln/ln_anno.c, ln/ln_close.c, ln/ln_comtx.c, ln/ln_comtx.h, ln/ln_db_lmdb.c, ln/ln_derkey.h, ln/ln_derkey_ex.c, ln/ln_derkey_ex.h, ln/ln_establish.c, ln/ln_node.c, ln/ln_normalope.c, ln/ln_print.c, ln/ln_script.c, ln/ln_script.h, ln/ln_signer.c, ln/ln_signer.h, ln/tests/test_ln_proto_acceptchannel.cpp, ln/tests/testinc_ln_bolt3_c.cpp, showdb/showdb.c
add `ln_derkey_ex.[ch]`
DB updated!
=>  ln: change the format of pub/priv keys

ln/ln.c, ln/ln_db_lmdb.c, ln/ln_derkey.c, ln/ln_derkey.h, ln/ln_derkey_ex.c, ln/ln_derkey_ex.h, ln/ln_establish.c, ln/ln_normalope.c, ln/ln_signer.c, ln/ln_signer.h, ln/tests/test_ln.cpp, ln/tests/test_ln_htlcflag.cpp, ln/tests/test_ln_proto_init.cpp, ln/tests/test_ln_proto_updateaddhtlc.cpp, ln/tests/test_ln_proto_updatechannel.cpp, ln/tests/test_ln_proto_updatefee.cpp, ln/tests/testinc_ln_bolt3_d.cpp, showdb/showdb.c
`ln_derkey_storage_get_next_index`
`ln_derkey_privkeys_get_current_storage_index`
`ln_derkey_privkeys_init`
`ln_derkey_privkeys_term`
=>  ln_derkey_ex: add functions

ln/ln.c, ln/ln_anno.c, ln/ln_comtx.c, ln/ln_db_lmdb.c, ln/ln_derkey.h, ln/ln_derkey_ex.c, ln/ln_derkey_ex.h, ln/ln_establish.c, ln/ln_print.c, ln/ln_signer.c, ln/tests/test_ln_proto_acceptchannel.cpp, ln/tests/testinc_ln_bolt3_c.cpp, showdb/showdb.c
=> ln_derkey_ex: refactor

ln/ln.c, ln/ln.h, ln/ln_close.c, ln/ln_comtx.c, ln/ln_db_lmdb.c, ln/ln_derkey_ex.c, ln/ln_derkey_ex.h, ln/ln_establish.c, ln/ln_print.c, showdb/showdb.c
=> ln: add `ln_funding_tx_t`

btc/btc_tx.h, ln/ln.c, ln/ln.h, ln/ln_close.c, ln/ln_comtx.c, ln/ln_db.h, ln/ln_derkey_ex.c, ln/ln_derkey_ex.h, ln/ln_establish.c, ln/ln_normalope.c, ln/ln_script.c, ln/ln_script.h, ln/ln_signer.c, ln/ln_signer.h, ln/tests/test_ln_proto_updateaddhtlc.cpp, ln/tests/testinc_ln_bolt3_c.cpp, ptarmd/lnapp.c, ptarmd/monitoring.c, ptarmd/wallet.c, showdb/showdb.c, tools/ctags.sh
remove the dependency with `ln_channel_t`
=> ln_signer: refactor... 

ln/ln_anno.c, ln/ln_anno.h, ln/ln_msg_anno.c
* fix gossip_timestamp_filter
* not send gossip_queries yet
* not allow gossip_queries yet
=> gossip_query: fix gossip_timestamp_filter

btc/btc_tx.c, btc/btc_tx.h, ln/ln_db_lmdb.c, ptarmcli/ptarmcli.c, ptarmd/btcrpc.h, ptarmd/btcrpc_bitcoind.c, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/monitoring.c, ptarmd/monitoring.h, ptarmd/ptarmd.c, ptarmd/ptarmd.h, ptarmd/tests/testinc_lnapp.cpp, ptarmd/wallet.c, ptarmd/wallet.h
* blockcount and feerate are watched by monitoring.c
* update JAR
* fixes
* `ptarmcli --paytowallet` fee calculation
=> btcprc: blockcount and feerate use cached value

ln/ln.h, ln/ln_db_lmdb.c
* initialize txn in `channel_db_open()`
* check DB power up!
=> fix lmdb: init txn

ln/ln.c, ln/ln.h, ln/ln_close.c, ln/ln_comtx.c, ln/ln_db_lmdb.c, ln/ln_establish.c, ln/tests/test_ln.cpp, ln/tests/test_ln_htlcflag.cpp, ln/tests/test_ln_proto_acceptchannel.cpp, ln/tests/test_ln_proto_init.cpp, ln/tests/test_ln_proto_openchannel.cpp, ln/tests/test_ln_proto_updateaddhtlc.cpp, ln/tests/test_ln_proto_updatechannel.cpp, ln/tests/test_ln_proto_updatefee.cpp, showdb/showdb.c
remove the dependency from `create_local_set_vin0_and_verify` to `ln_channel_t`
=> ln_comtx: refactor

ptarmd/cmd_json.c
fix JSON-RPC error message on `already connected`.
=> cmd_json: fix error message on "already connected"

ln/ln.h, ln/ln_db_lmdb.c, ln/ln_node.c, ln/ln_node.h, ptarmd/ptarmd.c, ptarmd/ptarmd.h, ptarmd/ptarmd_lib.c, ptarmd/ptarmd_main.c, ptarmd/tests/testinc_lnapp.cpp
* `ptarmd --color RRGGBB`
* fix `ptarmd -n ALIAS`
* check `ptarmd -a` routable
* check `ptarmd -n` length
=> change node property

ln/ln_db_lmdb.c, ln/ln_db_lmdb.h
=> reduce lmdb log

ptarmd/jni/btcj_jni.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h, ptarmd/ptarmd_main.c
execute script with absolute path.
=> script: use absolute path

ln/ln_comtx.c, ln/ln_db_lmdb.c
=>  ln: fix to delete the wrong assert call

ln/ln.c, ln/ln.h, ptarmd/cmd_json.c
invoiceのr-fieldに、指定されたamount_msat以上残っているshort_channel_idを追加する。
オプションで元に戻せるようにもしておく。
=> invoice rfield

options.mak
stop making if JVM file not found.
=> make: check JVM file

ptarmd/p2p_cli.c, ptarmd/p2p_svr.c
change max peer connections: 12 --> 6
* for performance
=> bitcoinj: max connection 12 --> 6

Makefile, ptarmd/cmd_json.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h
`ptarmcli -c`のエラーが分かりづらかったので、小分けした。
=> json: error

ptarmd/btcrpc_bitcoinj.c
* 1hour --> 3min
* bitcoinj retry
=> bitcoinj: change startup timeout

ln/ln.c, ln/ln.h, ln/ln_comtx.c, ln/ln_comtx.h, ln/ln_comtx_util.c, ln/ln_comtx_util.h, ln/ln_db_lmdb.c, ln/ln_establish.c, ln/ln_normalope.c, ln/tests/test_ln_proto_updateaddhtlc.cpp, ln/tests/testinc_ln_bolt3_c.cpp, ptarmd/lnapp.c, showdb/showdb.c
=> ln: rename

ptarmd/btcrpc_bitcoinj.c, ptarmd/jni/btcj_jni.c, ptarmd/jni/btcj_jni.h
* JAR: retry 3 times and throw exception
* ptarmd: wait 1min and exit
bitcoinjの起動時に、`awaitRunning()`から戻ってこないままになった場合の対応。
* `awaitRunning()`自体は10秒間隔で3回までリトライし、それでもダメな場合は`TimeoutException`を投げ、ptarmdがJARの失敗と判断して終了する。
* `awaitRunning()`から戻ってこないままになった場合、ptarmdが60秒まで待ち、JARの失敗と判断して終了する。
=> bitcoinj: retry

ln/ln_normalope.c, ln/tests/test_ln_proto_updatefee.cpp
use feerate service for testnet
* mainnet: https://bitcoinfees.earn.com/api/v1/fees/recommended
* testnet: https://api.blockcypher.com/v1/btc/test3
=> JAR: testnet fee service

ptarmd/monitoring.c
fix #1171
forget feerate update
=> fix pr #1171

ln/ln_db_lmdb.c, ptarmd/btcrpc_bitcoinj.c, ptarmd/jni/btcj_jni.c, ptarmd/lnapp.c
mutual close後、lnappのチャネルスレッドが終了せずに残っている。
その際に出るログが邪魔だったため、ついでに消した。
=> lnapp: close thread at closed or fail get status

ln/ln.h, ln/ln_cb.h, ln/ln_db_lmdb.c, ln/ln_normalope.c, ln/tests/test_ln_proto_updateaddhtlc.cpp, ptarmd/lnapp.c, ptarmd/monitoring.c, showdb/showdb.c, tests/4nodes_test/_all_test_st4fail1b.sh
=>  ln: refactor

install/script/closed.sh, install/script/connected.sh, install/script/disconnected.sh, install/script/error.sh, install/script/established.sh, install/script/fail.sh, install/script/forward.sh, install/script/fulfill.sh, install/script/htlcchanged.sh, install/script/payment.sh, install/script/started.sh
script: `jq -e '.'` and `bash`
=> ptarmd script

tests/4nodes_test/all_test.sh
=> tests: check liging proc num

ln/ln_db_lmdb.c, ln/ln_htlc.h, ln/ln_normalope.c, ln/tests/test_ln_htlcflag.cpp
=> ln: fix LN_HTLC_EMPTY and set ln_update_t::enabled

ln/ln.h, ln/ln_establish.c, ln/ln_establish.h, ln/ln_msg_establish.h, ln/tests/test_ln_proto_openchannel.cpp, ptarmcli/ptarmcli.c, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/ptarmd.h
`ptarmcli -f --private`でチャネルをprivateとして要求する。
未指定時はpublic channel。
=> open channel with private

ln/ln_anno.c, ln/ln_msg_anno.c, ln/ln_msg_anno.h
#1185 の現象を出すことができていない。
まず、localのchannel_announcementについては保存する前に署名のverifyを行うようにする。
=> issue #1185

ln/ln.c, ln/ln.h, ln/ln_comtx.c, ln/ln_comtx.h, ln/ln_comtx_util.h, ln/ln_db_lmdb.c, ln/ln_establish.c, ln/ln_normalope.c, ln/ln_update_info.h, ln/tests/test_ln.cpp, ln/tests/test_ln_htlcflag.cpp, ln/tests/test_ln_proto_acceptchannel.cpp, ln/tests/test_ln_proto_updateaddhtlc.cpp, ptarmd/lnapp.h, showdb/showdb.c
=> ln: add `ln_update_info.h`

ln/ln_db_lmdb.c
こことは別の実装をテストしていたときのことだが、`mdb_cursor_get()`で取得して、dataだけ書き換えて`mdb_cursor_put()`すると、エラーは出ないものの保存された結果が意図していない値になっていることがあった(`mdb_dump`などで確認)。
再現性があるのだがエラーにならない、keyを重複可能にしていないのに同じkeyで保存されているように見える、など、よくわからない挙動を示していた。
同じkeyを書き換えるからと思い、`mdb_cursor_get()`したkeyを`mdb_cursor_put()`でそのまま使っていたのだが、メモリを確保してそちらを`mdb_cursor_put()`に使うと大丈夫なように見えた。
おそらくだが、LMDBは`mdb_cursor_get()`でmmapしたアドレスを返していたので、`mdb_cursor_put()`する際にdataが増えるなどして位置がずれてもアドレスは追従しないため、異なった値をkeyとして使用していたのではないだろうか。
=> lmdb: copy key before mdb_cursor_put()

ln/ln_db_lmdb.c
announcementの送信済みnode_idリストであるannoinfo DBからnode_idを削除する際、残りがなければkeyごと削除していた。
しかし、元データであるannouncementはDBに残ったままなので、こちらもkeyだけは残しておく。そうしないと「今持つannouncementはすべてこのnode_idに対して送信済みだったものとする」という処理が難しくなってしまう。
=> lmdb: keep annoinfo if there is no sent node_id

ln/ln.c, ln/ln.h, ln/ln_commit_tx.c, ln/ln_db_lmdb.c, ln/ln_normalope.c, ln/ln_update.c, ln/ln_update.h, ln/ln_update_info.c, ln/ln_update_info.h, ln/tests/test_ln_htlcflag.cpp, ln/tests/test_ln_proto_updateaddhtlc.cpp, ptarmd/lnapp.c, ptarmd/monitoring.c, showdb/showdb.c
=>  ln_update_info: refactor

showdb/showdb.c
=> showdb: JSON

ln/ln_anno.c, ln/ln_db_lmdb.c, ln/ln_establish.c, ptarmd/jni/btcj_jni.c, ptarmd/lnapp.c
=> #warning --> //ToDo:

ln/ln_routing.cpp, tools/analyze_gossip.sh
announcement情報デバッグ用
* graphviz出力を復活(デフォルトでは無効。M_GRAPHVIZ有効時のみ)
* DBで保存しているannouncement数を吐き出すsh
=> debug: announcement info

ln/ln_db_lmdb.c
* show short_channel_id string
* remove M_DEBUG_KEYS
=> showdb: short_channel_id string

ln/ln.c, ln/ln_commit_tx.c, ln/ln_db_lmdb.c, ln/ln_normalope.c, ln/ln_update.c, ln/ln_update.h, ln/ln_update_info.h
=> ln_normalope: fix `max_accepted_htlcs` check

tests/4nodes_test/example_st5uni6666.sh
node4444-->3333-->5555->6666と送金するが、node_6666がfulflillせずにためたまま、node_6666がunilateral closeするつもり。
=> 4tests: no fulfill node_6666 and unilateral close

ptarmd/cmd_json.c
=> cmd_json: fix paytest

ln/ln.c, ln/ln_db_lmdb.c
use ln_init to initialize `ln_channel_t`
=> ln_db_lmdb: fix to abort in `channel_search`

ln/ln_cb.h, ln/ln_db_lmdb.c, ln/ln_normalope.c, ln/ln_normalope.h, ln/ln_update.h, ln/ln_update_info.c, ln/ln_update_info.h, ln/tests/test_ln_proto_updateaddhtlc.cpp, ptarmd/lnapp.c, ptarmd/lnapp.h, showdb/showdb.c
not next `update_idx`
DB updated!
=> use prev HTLC id to bind local channels in forwarding

ptarmd/cmd_json.c, ptarmd/cmd_json.h, ptarmd/lnapp.c
invoiceのチェック方法を修正。
ついでにlogも追加。
=> invoice check

btc/btc.c, docs/build_for_spv.md, docs/howtopay_starblocks.md, docs/testnet_2nodes_clightning.md, docs/testnet_2nodes_eclair.md, docs/testnet_2nodes_lnd.md, ln/ln.c, ln/ln.h, ln/ln_db_lmdb.c, ln/ln_node.c, options.mak, ptarmd/conf.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h, ptarmd/ptarmd_main.c, ptarmigan.cppcheck, tests/2nodes_test/example_st2.sh, tests/2nodes_test/example_st_conn.sh, tests/4nodes_test/example_st2.sh, tests/4nodes_test/example_st_conn.sh
`ptarmd`にchain種別を指定するオプションを追加する。
他のノードを参考にして、未指定の場合はmainnetとした。
その影響で、テスト用のスクリプトなどは変更が発生する。
lightning-integrationも変更すること。
=> ptarmd: add option

tests/2nodes_test/all_testj.sh, tests/2nodes_test/example_st3j.sh
=> tests: for bitcoinj

tests/4nodes_test/all_testj.sh, tests/4nodes_test/do_infinitej.sh, tests/4nodes_test/example_st3j.sh
=> bitcoinj tests

ptarmd/jni/btcj_jni.c, tests/2nodes_test/all_test.sh, tests/2nodes_test/all_testj.sh, tests/4nodes_test/all_test.sh, tests/4nodes_test/all_testj.sh
all_test.shに、簡易amountチェックを追加。
前後で`ptarmcli -l`の`total_local_msat`が変化したかどうかをチェックする。
値自体もチェックした方が老いのだろうが、とりあえず変わったかどうかだけにした。
=> all_tests: check amount

ptarmd/jni/btcj_jni.c
* rename JAR file
* slf4j-simple control
=> bitcoinj log

ptarmd/ptarmd_main.c
=> show library version

btc/btc.h, btc/btc_keys.c
=> btc: fix mPref size

tools/rpi_bj.sh
add setting script for Raspberry Pi bitcoinj version
=> tools: raspberry pi bitcoinj setting

ptarmd/btcrpc_bitcoinj.c, ptarmd/jni/btcj_jni.c, ptarmd/lnapp.c, ptarmd/ptarmd.c, ptarmd/ptarmd_main.c, utl/utl_log.c
* JAR update
* log
* thread join
=> bitcoinj startup

ln/ln.h, ptarmd/lnapp_manager.c, ptarmd/monitoring.c
to prune closed channels from memory by `monitor_thread`
=> ln: add `LN_STATUS_CLOSED`

ptarmd/btcrpc_bitcoinj.c, ptarmd/jar/ptarmd_lib.c, ptarmd/jni/btcj_jni.c, ptarmd/jni/btcj_jni.h, ptarmd/ptarmd.c, ptarmd/ptarmd_main.c
* bitcoinjの起動を別関数化
* bitcoinjの終了時にJVMのdestroyをしない(固まるため)
* 本来は修正可能かもしれないが、解決方法がわかってない
=> bj: restart/exit

docs/ptarmd.md
=> docs: ptarmd

ln/ln.c
=> status name: "closed"

ptarmcli/ptarmcli.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h
=> invoice: directory change

ln/Makefile, ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_db_lmdb.h, ln/ln_msg_x.h, ln/ln_msg_x_normalope.c, ln/ln_msg_x_payment.c, ln/ln_msg_x_payment.h, ln/ln_normalope.c, ptarmd/lnapp_cb.c
update_[fulfill|fail]_htlcをorigin nodeに返す部分の対応を忘れていたので、追加
=> use DB to forward between channels (2)

ln/ln.c, ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_normalope.c, ln/ln_update.h, ln/ln_update_info.c, ln/tests/test_ln_proto_updateaddhtlc.cpp, ptarmd/lnapp.c, ptarmd/lnapp_manager.c, ptarmd/lnapp_manager.h, ptarmd/monitoring.c, ptarmd/ptarmd.c
for each channel and removed when closed
add `ln_db_forward_add_htlc_create`
add `ln_db_forward_del_htlc_create`
=> ln_db: forward dbs is created explicitly

README.md, install/pay_fundin.py, ptarmd/btcrpc_bitcoind.c
minimal bitcoind version above v0.17
=> bitcoind version >= 0.17

ptarmd/lnapp.c, ptarmd/lnapp.h, ptarmd/monitoring.c, ptarmd/p2p.c
channels are locked only with `mux_conf`
=> lnapp: remove `mux_channel`

showdb/showdb.c
showdbのannounce済み一覧がJSON形式ではなかったため、対応。
=> Showdb announced

ln/ln_db_lmdb.c, ln/ln_db_lmdb.h, showdb/showdb.c, tests/4nodes_test/example_st5.sh
* `--listclosed` : show closed channel_id list
* `--showclosed CHANNEL_ID` : show selected channel information
=> showdb: closed option

ln/ln_db_lmdb.c
M_DB_DEBUG有効時に、txn beginカウンタをmutexする
=> ln_db: debug count mutex

ln/ln_normalope.c, ln/ln_normalope.h, ln/ln_update.c, ln/ln_update.h, ln/ln_update_info.c, ln/ln_update_info.h, ptarmd/lnapp.c, ptarmd/lnapp_manager.c
after sending update messages, clear the updates
when the channel are disconnected
before sending a `commitment_signed`
=> ln_normalope: cancel pending updates

ln/ln_commit_tx.c, ln/ln_normalope.c, ln/ln_update_info.c, ln/ln_update_info.h
after clearing pending updates
=> ln_normalope: save an inactive channel state

install/pay_fundin.py, install/pay_fundin.sh, ln/ln_establish.c, ln/ln_establish.h, ptarmcli/conf_cli.c, ptarmcli/ptarmcli.c, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/ptarmd.h
* `ptarmcli -f` use `push_msat` (not push_satoshi)
* max push_msat limitation(< 80% funding_sat)
=> ptarmd/cli: push_sat --> push_msat

ln/ln.c, ln/ln.h, ln/ln_commit_tx.c, ln/ln_db_lmdb.c, ln/ln_establish.c, ln/ln_establish.h, ln/ln_normalope.c, ln/ln_normalope.h, ptarmd/lnapp.c, tests/2nodes_test/log_filter.sh, tests/4nodes_test/_all_test_st4fail1b.sh, tests/4nodes_test/all_test.sh, tests/4nodes_test/all_testj.sh, tests/4nodes_test/log_filter.sh, tools/log_filter.sh
再接続時の`funding_locked`送信条件が間違っていたので修正
=> ln: fix and rename `ln_funding_locked_check_need` -> `ln_funding_locked_needs`

ln/ln_commit_tx.c, ln/ln_commit_tx.h, ln/ln_update_info.c, tests/2nodes_test/example_st_update_fee.sh
in local unilateral close
skip uncommitted updates
=> ln_commit_tx: peer's sigs does not match a commit tx

install/script/dbclosed.sh, ptarmd/monitoring.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h
=> ptarmd: channel db closed event

docs/showdb.md, showdb/showdb.c
* listwallet ==> paytowalletvin
* 秘密鍵やwitnessは隠す
=> showdb: command rename

ptarmcli/ptarmcli.c
* add long option name
* -q ==> --stop
* -h ==> --help
* -l ==> --getinfo
* fix: twice error message if invalid option used.
=> ptarmcli: add longopt

ptarmcli/ptarmcli.c
* addinvoice --> createinvoice
=> ptarmcli : rename

ln/ln.c, ln/ln.h, ln/ln_close.c, ln/ln_normalope.c, ln/ln_routing.cpp, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/monitoring.c, ptarmd/ptarmd.c, ptarmd/ptarmd.h, showdb/showdb.c
=> ln_close: fix to reconnect during closing negotiation

ptarmd/lnapp.c
block `ln_recv` and `ln_idle_proc` calls
=> lnapp: fix to block normal operation in closing

showdb/showdb.c
invoice DBが使われなくなったので、`showdb -i`で代わりにpreimage DBの方を使う。
=> showdb: show preimage

ln/ln_commit_tx.c, ln/ln_commit_tx.h, ln/tests/test_ln.cpp, ln/tests/test_ln_htlcflag.cpp, ln/tests/test_ln_proto_acceptchannel.cpp, ln/tests/test_ln_proto_openchannel.cpp, ln/tests/test_ln_proto_updateaddhtlc.cpp, ln/tests/test_ln_proto_updatefee.cpp, ptarmd/monitoring.c, tools/log_filter.sh
in remote unilateral close
skip uncommitted updates
=>  ln_commit_tx: local sigs does not match a remote commit tx

ln/ln.c, ln/ln.h, ln/ln_commit_info.h, ln/ln_commit_tx.c, ln/ln_commit_tx.h, ln/ln_db_lmdb.c, ln/ln_derkey_ex.c, ln/ln_derkey_ex.h, ln/ln_establish.c, ln/ln_normalope.c, ln/ln_print.c, ln/ln_wallet.c, ln/ln_wallet.h, ln/tests/test_ln.cpp, ln/tests/test_ln_htlcflag.cpp, ln/tests/test_ln_proto_acceptchannel.cpp, ln/tests/test_ln_proto_openchannel.cpp, ln/tests/test_ln_proto_updateaddhtlc.cpp, ln/tests/test_ln_proto_updatefee.cpp, ptarmd/monitoring.c
=> ln: add `LN_STATUS_CLOSE_UNI_REMOTE_SECOND_LAST`

ptarmd/cmd_json.c
fix #1358 
unilateral close to not connected channel.
=> issue #1358

ln/ln_db_lmdb.c, ptarmd/ptarmd_main.c
* tar current db
* remove anything except channel_db
* remove anything except version
=> ptarmd --clear_channel_db

docs/howtouse.md, docs/ptarmcli.md
* add: `--initroutesync` option
* comment out: `--debug`
=> docs: initroutesync

install/pay_fundin.py
* return error code
* filename 'json' returns JSON
=> payin.py return error_code

docs/howtouse.md
=> docs: add more `--initroutesync` information

install/pay_fundin.py
=> ptarmcli fund: fix push_msat

ln/ln_db_lmdb.c, ln/ln_routing.cpp
issue #1393 関連
再現できないのでログを追加する。
=> issue#1393: add log

version.h
=> fix : apply current version

ln/ln_routing.cpp
=> routing: log

ptarmd/lnapp.c, ptarmd/tests/test_lnapp_anno.cpp
Create announcement data before sending to reduce DB lock time.
=> ptarmd: create announcement data before send

docs/howtouse.md, docs/ptarmcli.md, ptarmcli/ptarmcli.c, ptarmd/cmd_json.c
`ptarmcli --listpayment=PAYMENT_ID`
=> listpayment: parameter PAYMENT_ID

docs/howtouse_rest_api.md, ptarmapi/.env-sample, ptarmapi/README.md, ptarmapi/src/bitcoin/bitcoin.service.ts, ptarmapi/src/config/ptarmigan.ts, ptarmapi/src/main.ts, ptarmapi/src/ptarmigan/ptarmigan.controller.ts, ptarmapi/src/ptarmigan/ptarmigan.service.ts
fix issue removeinvoice, removeinvoices
add documentation
change port to rpc port
=> fix rest-api

ptarmd/ptarmd_main.c
=> version: fix jsonrpc-c version string

README.md, docs/howtouse.md
=> testnet reference

install/pay_fundin.py
=> fix pay_fundin.py

ptarmd/lnapp.c, ptarmd/lnapp_cb.c
workaround for write-timeout
peer node's problem?
=> ptarmd: number of gossip unit to send 10 -> 1

version.h
=> version string: 0.2.1

ptarmd/btcrpc_bitcoind.c, tests/2nodes_test/example_st1.sh, tests/2nodes_test/example_st3.sh, tests/2nodes_test/example_st3j.sh, tests/4nodes_test/example_st1.sh, tests/4nodes_test/example_st3.sh, tests/4nodes_test/example_st3j.sh, tests/testfiles/generate.sh, tests/testfiles/regtest.conf
bitcoind v0.18.x (and v0.17.x)
* `generate` --> `generatetoaddress`
* `signrawtransaction` --> `signrawtransactionwithwallet`
=> Bitcoind 0 18

docs/howtouse.md, tools/regtesttest.conf, tools/regtesttest.sh
easy test tool for install folder
* start regtest
* start 2 ptarmd nodes
* fund using `pay_fundin.py`
* open
* pay
* close
* quit
=> tools: easy install test tool

tools/regtesttest.sh
=> tools: regtesttest: bitcoind v0.18

ln/ln.c, ln/ln_db_lmdb.c, ln/ln_htlc_tx.c, ptarmd/monitoring.c, ptarmd/wallet.c
1. channel established(A and B)
2. A) archive `db` folder
3. reconnect
4. some payment...
5. A) extract archived `db` folder
6. A) unilateral close
7. B) start
8. B) ABORT
=> fix: revoked transaction close

ptarmd/jni/btcj_jni.c, ptarmd/jni/btcj_jni.h
* bitcoinj sometime fail startup, so if block downloading is not progressing, abort `ptarmd`.
* ptarmigan-jar: f4913c742e5e105c5ceb7eb83a379923917547c9
=> [spv]startup timeout

ln/ln_commit_tx_util.c, ln/ln_derkey.c
use `btc_md_sha256cat()` instead of directly call MbedTLS API.
=> use sha256cat

ln/ln_msg_anno.c, ln/ln_msg_close.c, ln/ln_msg_establish.c, ln/ln_msg_normalope.c, ln/ln_msg_setupctl.c, ln/ln_print.c, utl/utl_log.c, utl/utl_log.h
remove `gcc -DPTARM_UTL_LOG_MACRO_DISABLED` error
=> remove error on `PTARM_UTL_LOG_MACRO_DISABLED`

showdb/showdb.c
#1462 
`showdb -v` use genesis block.
=> showdb: fix chain name

docs/ptarmcli.md, ln/ln_invoice.h, ptarmcli/ptarmcli.c, ptarmd/cmd_json.c
`ptarmcli --createinvoice AMOUNT_MSAT --description DESCRIPTION`
default: (empty string)
=> createinvoice: add description

README.md, docs/ptarmd.md, ln/ln_db_lmdb.c, ln/ln_node.c, ptarmd/btcrpc.h, ptarmd/btcrpc_bitcoind.c, ptarmd/btcrpc_bitcoinj.c, ptarmd/conf.c, ptarmd/conf.h, ptarmd/ptarmd.h, ptarmd/ptarmd_main.c
read `rpcuser`, `rpcpassword` and `rpcport` from bitcoin.conf.
=> bitcoind.conf check only RPC

docs/ptarmd.md, ptarmd/conf.c, ptarmd/ptarmd_main.c
--bitcoinrpcuser
--bitcoinrpcpassword
--bitcoinrpcport
=> add bitcoin RPC option

ln/ln_db_lmdb.c, ptarmcli/ptarmcli.c, ptarmd/cmd_json.c
* `ptarmcli --listinvoice=PAYMENT_HASH`
=> listinvoice option

ln/ln.h, ptarmapi/src/model/invoice.ts, ptarmapi/src/model/list-invoice.ts, ptarmapi/src/ptarmigan/ptarmigan.controller.ts, ptarmcli/ptarmcli.c, ptarmd/cmd_json.c
* `ptarmcli --createinvoice --invoiceexpiry`
* REST-API
* createinvoice: add "descrption" and "invoiceExpiry"
* listinvoice: add "paymentHash"
=> ptarmcli createinvoice: add `--invoiceexpiry` option

ln/ln_establish.c
through if open_channel received on opened socket.
=> open_channel: through if open_channel received on opened socket

install/script/addfinal.sh, install/script/closed.sh, install/script/connected.sh, install/script/dbclosed.sh, install/script/disconnected.sh, install/script/error.sh, install/script/established.sh, install/script/fail.sh, install/script/forward.sh, install/script/fulfill.sh, install/script/htlcchanged.sh, install/script/payment.sh, install/script/started.sh, ptarmd/jni/btcj_jni.c
* reduce bitcoinj log
* rewrite script
=> reduce bitcoinj log

ln/ln_db_lmdb.c
=> fix db update

ptarmd/p2p.c
暫定で`gethostbyname()`を使い、最初のメンバーだけ使って`connect()`する。
=> gethostbyname

install/script/started.sh, ptarmcli/conf_cli.c, ptarmcli/ptarmcli.c, ptarmd/btcrpc_bitcoind.c, ptarmd/cmd_json.c, ptarmd/conf.c, ptarmd/lnapp.c, ptarmd/p2p.c, ptarmd/ptarmd.c, ptarmd/ptarmd_main.c
#1484 
* `gethostbyname()` --> `getaddrinfo()`
* use `strncpy()` or check length more
=> use getaddrinfo() to resolve name.

libs/Makefile
download boost.tar.gz from dl.bintray.com or sourceforge.net
=> download boost.tar.gz once

install/script/payment.sh, ln/ln_node.c, ln/ln_node.h, ln/tests/test_ln_node.cpp, ptarmcli/ptarmcli.c, ptarmd/cmd_json.c, ptarmd/ptarmd_main.c, utl/utl_net.c, utl/utl_net.h
* `ptarmd --announceip` allow name
* connect string (add `ptarmcli --connaddr NAME`)
* `ptarmd --annoucneip` allow local address
#1484
=> resolve name

ln/ln.c, ln/ln_db_lmdb.c, ptarmd/btcrpc.h, ptarmd/btcrpc_bitcoind.c, ptarmd/btcrpc_bitcoinj.c, ptarmd/jni/btcj_jni.c, ptarmd/lnapp.c, ptarmd/lnapp_cb.c, ptarmd/monitoring.c, ptarmd/ptarmd.c, ptarmd/tests/testinc_lnapp.cpp
* `btcrpc_get_confirmations()` call monfunc.
* `btcrpc_getblockcount()` can get blockhash.
* update JAR
=> monitoring: AppConf.confirmation update only monitoring

ptarmd/lnapp.c, ptarmd/monitoring.c
=> disconnect before exchange funding_locked

ln/ln_setupctl.c, ln/ln_setupctl.h
fix `ENABLE_DEVELOPER_MODE=1` build
=> fix: developer_mode build

ptarmapi/src/model/list-payment.ts, ptarmapi/src/ptarmigan/ptarmigan.controller.ts
- Add listpayment=N to REST API
`../ptarmcli --listpayment=0` 
- Change name `executeListPaymentState` to `executeListPaymentsState`
=> Add listpayment=N to REST API

docs/build_for_spv.md, install/jdk.sh, options.mak, tools/rpi_bj.sh
* cross compile for SPV mode need libjvm.so using target environment.
* copy `libs/jre/lib/client/`
* use OpenJDK8
=> cross compile for SPV mode

ptarmd/btcrpc.h, ptarmd/btcrpc_bitcoind.c, ptarmd/btcrpc_bitcoinj.c, ptarmd/jni/btcj_jni.c, ptarmd/jni/btcj_jni.h, ptarmd/monitoring.c, ptarmd/tests/testinc_lnapp.cpp, ptarmd/wallet.c
* update JAR
* add peer node_id to `btcprc_is_tx_broadcasted()`
=> spv: check closing faster test

options.mak
auto cross compile for ARM
* use bitcoinj
* JVM=ARM
=> auto cross compile for ARM

ptarmd/conf.c, ptarmd/conf.h, ptarmd/ptarmd.c, ptarmd/ptarmd.h, ptarmd/ptarmd_main.c, ptarmd/tests/testinc_lnapp.cpp
change `minimum_depth` default value
* mainnet=3
* other=1
=> minimum_depth: change default value

ln/ln.h, ptarmd/monitoring.c
set `last_confirm` as `last_check_confm` to shorten closing check time.
=> set unspent confirmation

Makefile, ptarmcli/ptarmcli.c, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/monitoring.c, ptarmd/wallet.c, ptarmd/wallet.h
change `ptarmcli --paytowallet` result
* add vin list
=> change `paytowallet` result

tests/2nodes_test/all_test.sh, tests/2nodes_test/all_test_uni.sh, tests/2nodes_test/all_testj.sh, tests/2nodes_test/all_testj_uni.sh, tests/2nodes_test/test_after_uni2.sh, tests/2nodes_test/test_after_uni3.sh, tests/2nodes_test/test_after_uni4.sh, tests/testfiles/generate.sh
* local close, received HTLC
* remote close, offered HTLC
* remote close, received HTLC
=> unilateral close tests

tests/2nodes_test/example_st2.sh, tests/2nodes_test/test_after_uni1.sh, tests/2nodes_test/test_after_uni2.sh, tests/2nodes_test/test_after_uni3.sh, tests/2nodes_test/test_after_uni4.sh
bitcoinj version tests use more blockcount.
=> tests: use relative blockcount

tests/2nodes_test/test_after_uni2.sh, tests/2nodes_test/test_after_uni3.sh, tests/2nodes_test/test_after_uni4.sh
=> tests: fix scripts

ptarmd/btcrpc_bitcoind.c, ptarmd/btcrpc_bitcoinj.c, tests/2nodes_test/all_test_uni.sh, tests/2nodes_test/all_testj_uni.sh, tests/2nodes_test/example_st1.sh, tests/2nodes_test/example_st3j.sh, tests/2nodes_test/test_after_uni1.sh, tests/2nodes_test/test_after_uni2.sh, tests/2nodes_test/test_after_uni3.sh, tests/2nodes_test/test_after_uni4.sh
* fix unilateral close test script
* add test description
=> tests: fix script

tests/2nodes_test/all_test.sh, tests/2nodes_test/all_test_uni.sh, tests/2nodes_test/all_testj.sh, tests/2nodes_test/all_testj_uni.sh, tests/2nodes_test/test_after.sh, tests/2nodes_test/test_after_uni1.sh, tests/2nodes_test/test_after_uni2.sh, tests/2nodes_test/test_after_uni3.sh, tests/2nodes_test/test_after_uni4.sh, tests/2nodes_test/testd_prepare.sh, tests/2nodes_test/testj_prepare.sh, tests/4nodes_test/all_test.sh, tests/4nodes_test/all_testj.sh
=> fix: ==  --> =

tests/2nodes_test/test_after_uni3.sh, tests/2nodes_test/test_after_uni4.sh
fix unilateral close test scripts
=> fix unilateral test scripts

ln/ln.h, ln/ln_anno.c
check short_channel_id error
* `create_local_channel_announcement()` error
* short_channel_id == 0
=> ln: check short_channel_id error

ptarmd/btcrpc.h, ptarmd/btcrpc_bitcoinj.c, ptarmd/ptarmd.c
* SPV log
* "CONT=" : log output and continue
* "STOP=" : log output and stop
* "BLOCK=" : log output(block height) and continue
* SPV timeout counter
* not count down if "BLOCK=" height changing.
=> change spv log format

ln/ln_db_lmdb.c, ptarmcli/ptarmcli.c, ptarmd/ptarmd.c, ptarmd/wallet.c
=> gcc-8: format-truncation

ln/ln_normalope.c
callback `htlcchanged.sh` after HTLC cleared.
=> callback after irrevocably committed

ln/ln_anno.c
#1539 
`funding_locked`交換前に`announcement_signatures`を受信した場合、unilateral closeせずにスルーする。
`announcement_signatures`がBOLT7系メッセージなので、他の場合もスルーするように変更。
=> ignore announcement_signatures before funding_locked

ln/ln_normalope.c
Ignore receiving check `update_fee.feerate_per_kw` range without mainnet.
Testnetの場合、feerate serviceの値がbitcoindの値と乖離している場合が多いため、チェックから除外する(regtestはそもそも意味が無いため、チェックしない)。
ただし、minimumのfeerate_per_kw(253)より小さい場合にはエラーとする。
=> receive update_fee: ignore feerate_per_kw without mainnet

ln/ln_normalope.c
=> fix PR#1551

ptarmapi/script/htlcchanged.sh, ptarmapi/src/app.module.ts, ptarmapi/src/auth/auth.module.ts, ptarmapi/src/ptarmigan/ptarmigan.controller.ts
htlcchanged.sh can not post. fixed it.
=> fix htlcchanged.sh in rest api

tests/4nodes_test/all_test.sh, tests/4nodes_test/all_testj.sh, tests/4nodes_test/example_st1.sh, tests/4nodes_test/example_st2.sh, tests/4nodes_test/example_st_conn.sh, tools/log_filter.sh
* payment: 5sec ==> 6sec
* ignore confirm error for SPV
=> tests: change timing

ptarmcli/ptarmcli.c, ptarmd/cmd_json.c
invoiceにr-fieldを付加しないオプション `--no-rfield`を追加。
`--createinvoice`のみ有効。
オプション無しの場合、現状と同じ。
すなわち、要求するamount_msatを満たすchannelをr-fieldとして追加している。満たすchannelがない場合はメッセージとして出力もさせている。
が、eclairの動作を見る限りでは`announcement_signatures`を送信する6conf以降、つまり`channel_announcement`しかroutingに使っていないように見える。
おそらく現状でのモバイルLightning決済はEclair Mobileが多いだろう(今後は知らんが)。
`--no-rfield`により、所有するchannelの数とnvoiceのサイズは関係が無くなる。つまり、invoiceの文字数が小さくなることが期待できる。
=> ptarmcli --no-rfield

install/script/started.sh, ptarmd/ptarmd.c
=> started.sh: local_msat

btc/Makefile, btc/btc_crypto.c, btc/btc_tx.c, btc/examples/Makefile, btc/tests/Makefile, libs/Makefile, ln/Makefile, ln/ln_db_lmdb.c, ln/ln_derkey.c, ln/ln_routing.cpp, ln/tests/Makefile, ln/tests/testinc_ln_bolt3_e.cpp, options.mak, ptarmcli/Makefile, ptarmd/Makefile, ptarmd/btcrpc_bitcoinj.c, ptarmd/cmd_json.c, ptarmd/ptarmd.c, ptarmd/ptarmd_main.c, ptarmd/tests/Makefile, ptarmd/wallet.c, routing/Makefile, showdb/Makefile, utl/utl_dbg.h
* USE_OPENSSL: SHA256 and some derkey function
* fix DISABLE_PRINTFUND
* gcc -O3
=> faster receive

tools/rpi_bj.sh
* USE_OPENSSL=1
* DISABLE_PRINTFUND=1
=> RasPi: faster option

ptarmd/btcrpc_bitcoinj.c
=> bitcoinj: check invalid txid

version.h
=> working version

ptarmd/lnapp.c
`ptarmcli --getinfo`: show `announcement_signatures`
=> getinfo: announcement_signatures

ln/ln.c, ptarmd/lnapp.c
NORMAL OPERATIONへの遷移を`funding_locked`交換後にする。
=> set "normal operation" after funding_locked

ptarmd/btcrpc.h, ptarmd/btcrpc_bitcoind.c, ptarmd/btcrpc_bitcoinj.c, ptarmd/jni/btcj_jni.c, ptarmd/jni/btcj_jni.h, ptarmd/monitoring.c, ptarmd/ptarmd.c
`ptarmd` not abort but quit if JAR exception happened.
=> SPV: ptarmd quit if JAR exception happened.

ln/ln_anno.c, ln/ln_msg_anno.c, ln/ln_msg_anno.h, tests/2nodes_test/all_testj.sh, tests/2nodes_test/clean.sh, tests/2nodes_test/example_st1.sh, tests/2nodes_test/example_st2.sh, tests/2nodes_test/example_st_conn.sh, tests/2nodes_test/test_after.sh, tests/4nodes_test/all_testj.sh, tests/4nodes_test/clean.sh, tests/4nodes_test/example_st1.sh, tests/4nodes_test/example_st2.sh, tests/4nodes_test/example_st3.sh, tests/4nodes_test/example_st3j.sh, tests/4nodes_test/example_st_conn.sh, tools/log_filter.sh
自分がfunding_lockedしていない状態でもannouncement_signaturesを受信することはあり得るため、スルーせずに保存する。
=> fix received announcement_signatures

ln/ln_db_lmdb.c
=> fix anno_prune

ln/ln_anno.c, ln/ln_db.h, ln/ln_db_lmdb.c, ln/ln_msg_anno.c, ln/ln_msg_anno.h, options.mak, ptarmd/lnapp.c, ptarmd/lnapp_util.c
=> gossip query

ptarmd/cmd_json.c, ptarmd/conf.c
* support `[SECTION]` format
* not support: `SECTION.parameter` format
=> bitcoin.conf section after v0.17

btc/btc_tx_buf.c, btc/btc_tx_buf.h, btc/tests/testinc_tx_buf.cpp
add big endian varint type for TLV format.
=> add big endian varint

ptarmd/btcrpc.h, ptarmd/btcrpc_bitcoind.c, ptarmd/btcrpc_bitcoinj.c, ptarmd/jni/btcj_jni.c, ptarmd/jni/btcj_jni.h, ptarmd/lnapp_cb.c, ptarmd/monitoring.c, ptarmd/ptarmd.c, ptarmd/tests/testinc_lnapp.cpp, tests/2nodes_test/all_testj_uni.sh
* `btcrpc_set_channel()` : return bool
* remove unused Java API
=> Fix unspent

ptarmd/monitoring.c
* jar: commit 3b527a74233dc8d3d083081dca150cf5f3e29373
commit cbb3ed03d44a155a1231363e0d5d83481a51b6b4
Date:   Tue Sep 24 23:15:55 2019 +0900
jar: v0.0.5
commit 3b527a74233dc8d3d083081dca150cf5f3e29373
commit eb6541856905e33c81df41f8484c38d68a28ec1e
Date:   Mon Sep 23 22:49:03 2019 +0900
update JAR
983ec243307c5fd3a3a00dd728ae73cd2178cf08
commit 4d463c1501450d6cc14b95382d8aef7dca889c52
Date:   Fri Sep 20 18:05:34 2019 +0900
update JAR
commit 26bac66bef3acc7faa5a3e66ce4c7d6ec298b709
Date:   Fri Sep 20 17:30:58 2019 +0900
Don't save if vin count == 0
=> jar: v0.0.5

ln/ln.c, ptarmd/cmd_json.c, ptarmd/lnapp.c, ptarmd/lnapp.h, ptarmd/lnapp_manager.c, ptarmd/p2p.c
=> separate lnapp_stop()

ptarmd/lnapp.c, ptarmd/lnapp.h, ptarmd/p2p.c
https://github.com/nayutaco/lns_arduino_library/issues/10
call `ln_init()` before noise handshake starts.
=> Reduced waiting time for noise handshake transmission

ln/ln_db_lmdb.c
#1605 
recent gcc support "format truncation"
=> gcc: format truncation

ln/ln_db_lmdb.c, ptarmd/ptarmd.c, utl/utl_common.h
=> gcc: fixed size %s

README.md, libs/Makefile, ptarmd/ptarmd_main.c
* show OpenSSL version
* update OpenSSL: v1.1.1d
=> version: add OpenSSL version

ptarmd/ptarmd.c
exit ptarmd if set_channel() failed.
=> Fail setchannel

install/default_conf.sh, install/script/error.sh, ln/ln.c, ln/ln.h, ln/ln_cb.h, ln/ln_establish.c, ln/ln_normalope.c, ln/ln_setupctl.c, ln/tests/test_ln.cpp, ptarmd/conf.c, ptarmd/lnapp_cb.c, ptarmd/lnapp_util.c, ptarmd/lnapp_util.h, ptarmd/ptarmd.c, ptarmd/ptarmd.h
configure feerate_per_kw limit
* add `feerate_min` and `feerate_max` in channel.conf
* use `feerate_min` and `feerate_max` to check establish and `update_fee`
* call error.sh when sending `error` message
=> Feerate limit

ptarmd/lnapp.c, ptarmd/lnapp.h
call log: lnapp_stop_and_join()
=> log: lnapp_stop_and_join()

ln/ln_establish.c, ln/ln_normalope.c
fix `update_fee` min/max check
=> fix update_fee check

ptarmd/ptarmd.c
=> lnshield log: fix

ln/Makefile, ln/ln_tlv.c, ln/ln_tlv.h, ln/tests/Makefile, ln/tests/test_ln_tlv.cpp
=> TLV parser

utl/utl_net.c
make test compile error on gcc8.
=> tests: gcc warning

ptarmd/btcrpc_bitcoinj.c, ptarmd/jni/btcj_jni.c, ptarmd/jni/btcj_jni.h
* ptarmigan-bitcoinj: v0.1.1
* call removeSuspendBlock() if ALL sync done.
=> Bj remove suspend block

ln/ln.c, ln/ln.h, ln/ln_anno.c, ln/ln_msg_setupctl.c, ln/ln_setupctl.c, ln/ln_setupctl.h, ln/tests/Makefile, ln/tests/test_ln_anno.cpp, ln/tests/test_ln_init.cpp, ln/tests/test_ln_proto_init.cpp, ptarmd/conf.c, ptarmd/ptarmd.h, showdb/showdb.c
* fix features endian
* latest check items
* update tests
=> fix features endian and update check items

ln/ln.c, ln/ln.h, ln/ln_db_lmdb.c, ln/ln_derkey_ex.c, ln/ln_derkey_ex.h, ln/ln_establish.c, ln/ln_normalope.c, ln/ln_setupctl.c, ln/ln_setupctl.h, ln/ln_version.h, ln/tests/test_ln_init.cpp, ptarmd/conf.c, showdb/showdb.c
=> static_remotekey

btc/btc_tx.c, btc/btc_tx.h
=> elements: init value

btc/btc_script.c, btc/btc_script.h, btc/btc_sw.c, btc/examples/tx_create_copy.c, ln/ln_wallet.c
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-August/013014.html
```
NG:
uint8_t FALSE=0;
const utl_buf_t WIT_NULL = { &FALSE, 1 };
OK:
const utl_buf_t WIT_NULL = { NULL, 0 };
```
=> BTC: check zero witness

Makefile, btc/examples/Makefile_ptarmbtc, btc/examples/tx_create_copy.c
`make btconly` add example source file.
=> make btconly

ln/ln_db_lmdb.c, ln/ln_normalope.c, options.mak, ptarmcli/ptarmcli.c, ptarmd/cmd_json.c
add `ptarmcli --importpreimage` for submarine swap
* compile switch: `ENABLE_CMD_IMPORTPREIMAGE=1` on options.mak
=> cli: importpreimage
